import { renderWorkbench, type UIState, type TabId } from '../src/ui';
import { makeWorkbenchFixture } from '../tests/fixtures/workbench';
import { DEFAULT_SETTINGS, emptyWorkbenchData } from '../src/domain';
const container=document.getElementById('app')!;
const state:UIState={data:makeWorkbenchFixture('2026-10-01'),settings:DEFAULT_SETTINGS,period:{start:'2026-09-28',end:'2026-10-04'},today:'2026-10-01',tab:'home',search:'',project:'',warnings:[]};
const params=new URLSearchParams(location.search);if(params.has('empty'))state.data=emptyWorkbenchData();if(params.has('scope')&&state.data.projects[0]){state.project=state.data.projects[0].id;state.data.projects[0].description=params.get('scope')==='real'?'真实范围：只交付接入模块；验收：边界用例通过。':params.get('scope')==='placeholder'?'请填写范围、目标和验收边界':'';}if(params.has('unknown')){const t=state.data.tasks[0];t.title='【虚构】未知排期任务';t.executor='fixture-a';t.executors=['fixture-a','fixture-b'];t.originalStart='';t.originalDue='';t.forecastDue='';t.remainingHours=null;t.allocations=[];t.status='in-progress';state.data.tasks=[t];state.data.modules=[];state.data.people=[{id:'fixture-a',name:'虚构甲',capacity:{hoursPerDay:8}},{id:'fixture-b',name:'虚构乙',capacity:{hoursPerDay:8}}];const m=state.data.meetings?.[0];if(m){m.actions=[{id:'fixture-action',text:'核对未知任务',taskId:t.id,due:'2099-12-31',owner:'old-owner',state:'open'}];state.data.meetings=[m];}};if(['home','projects','people','meetings','materials','weekly'].includes(params.get('tab')||''))state.tab=params.get('tab') as TabId;
function showRecord(title:string,record:unknown){document.getElementById('detail')?.remove();const dialog=document.createElement('dialog');dialog.id='detail';const h=document.createElement('h2');h.textContent=title;const body=document.createElement('pre');body.textContent=JSON.stringify(record,null,2);const close=document.createElement('button');close.textContent='关闭';close.onclick=()=>dialog.close();dialog.append(h,body,close);document.body.append(dialog);dialog.showModal();}
function render(){renderWorkbench(container,state,{projectDetail:id=>{state.selectedProject=id;state.projectTab='overview';render()},projectTab:tab=>{state.projectTab=tab;render()},meeting:m=>showRecord(m.title,m),createMeeting:()=>{},material:v=>showRecord(v.title+' · '+v.version,v),createMaterial:()=>{},openMaterial:()=>{},tab:id=>{state.tab=id;state.selectedProject='';history.replaceState(null,'',`?tab=${id}`);render()},search:value=>{state.search=value;render()},project:value=>{state.project=value;render()},period:p=>{state.period=p;render()},task:task=>{document.getElementById('detail')?.remove();const dialog=document.createElement('dialog');dialog.id='detail';const heading=document.createElement('h2');heading.textContent=task.title;const text=document.createElement('pre');text.textContent=JSON.stringify(task,null,2);const close=document.createElement('button');close.textContent='关闭';close.onclick=()=>dialog.close();dialog.append(heading,text,close);document.body.append(dialog);dialog.showModal();},open:()=>{},create:()=>{},createRecord:()=>{},import:()=>{},progress:()=>{},summary:()=>{},baseline:()=>{},chooseBaseline:id=>{state.baselineId=id;render()},refresh:render,settings:()=>{}});}
render();
