import { formatLocalDateTime, toLocalDateTimeInput, localDateTimeToISO } from './time';
import { App, Modal, Notice, FileSystemAdapter, Platform, TFile } from 'obsidian';
import { taskExecutors } from './domain';
import type { WorkbenchData, Meeting, MeetingAction, MaterialVersion, Task } from './domain';
import { getAdoptedVersion, getLatestAdoption, validateMeeting, validateMaterialVersion, taskTrace } from './knowledge';
import { inspectPrototypeFiles, previewPrototypeZip, validateExternalUrl, validateEntry, validateRelativePath, type PrototypePlan } from './prototype-security';
import { VaultStore } from './store';
export interface KnowledgeHost { app:App; data:WorkbenchData; store:VaultStore; reload():Promise<void>; openFile(path?:string):void; openTask(task:Task):void; }
const id=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const message=(error:unknown)=>error instanceof Error?error.message:String(error);
function n<K extends keyof HTMLElementTagNameMap>(tag:K,cls='',text?:string){const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function b(parent:HTMLElement,label:string,action:()=>void,primary=false){const button=n('button',primary?'mod-cta':'',label);button.type='button';button.addEventListener('click',action);parent.append(button);return button;}
function field(parent:HTMLElement,label:string,value='',type='text'){const wrap=n('label','',label);const input=type==='textarea'?n('textarea'):n('input');if(type!=='textarea')(input as HTMLInputElement).type=type;input.value=value;input.setAttribute('aria-label',label);wrap.append(input);parent.append(wrap);return input;}
function pick(parent:HTMLElement,label:string,options:{value:string;label:string}[],value=''){const wrap=n('label','',label),select=n('select');select.setAttribute('aria-label',label);for(const option of options){const e=n('option','',option.label);e.value=option.value;select.append(e);}select.value=value;wrap.append(select);parent.append(wrap);return select;}
function section(parent:HTMLElement,title:string){const details=n('details','elw-form-section');details.append(n('summary','',title));const content=n('div','elw-form');details.append(content);parent.append(details);return content;}
const lines=(value:string)=>value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
function checkList(parent:HTMLElement,label:string,options:{value:string;label:string}[],selected:readonly string[]=[]){const details=n('details','elw-form-section');details.append(n('summary','',label));const boxes=new Map<string,HTMLInputElement>();for(const option of options){const row=n('label','elw-check-row'),box=n('input');box.type='checkbox';box.checked=selected.includes(option.value);row.append(box,n('span','',option.label));details.append(row);boxes.set(option.value,box);}parent.append(details);return ()=>[...boxes].filter(([,box])=>box.checked).map(([value])=>value);}
export class KnowledgeConfirmModal extends Modal {
  constructor(app:App,private title:string,private text:string,private label:string,private apply:()=>Promise<void>){super(app);}
  onOpen(){this.contentEl.classList.add('elw-modal');this.contentEl.append(n('h2','',this.title),n('div','elw-preview',this.text));const error=n('div','elw-error');error.setAttribute('role','alert');this.contentEl.append(error);const actions=n('div','elw-modal-actions');const cancel=b(actions,'取消',()=>this.close());const save=b(actions,this.label,()=>{save.disabled=true;cancel.disabled=true;void this.apply().then(()=>this.close()).catch(e=>{error.textContent=message(e);save.disabled=false;cancel.disabled=false;});},true);this.contentEl.append(actions);}
  onClose(){this.contentEl.replaceChildren();}
}
function meetingText(meeting:Meeting,data:WorkbenchData){const confirmed=meeting.decisions.filter(d=>d.state==='confirmed'),other=meeting.decisions.filter(d=>d.state!=='confirmed');return `${meeting.title}\n${formatLocalDateTime(meeting.startAt)} · 项目 ${meeting.project}\n参会 ${meeting.participants.join('、')}\n\n已确认决策\n${confirmed.map(d=>`• ${d.text}`).join('\n')||'无'}\n\n未决事项\n${meeting.unresolved.map(t=>`• ${t}`).join('\n')||'无'}\n\n行动项\n${meeting.actions.map(action=>{const task=data.tasks.find(t=>t.id===action.taskId);return `• ${action.text}｜${task?`任务 ${task.id} · ${taskExecutors(task).map(id=>id||'未分配').join('、')||'未分配'} · ${task.forecastDue||'未评估'}`:`${action.owner||'未分配'} · ${action.due||'未定日期'}`}｜${action.state==='done'?'已完成':'待办'}`;}).join('\n')||'无'}\n\n讨论 / 建议（未确认）\n${other.map(d=>`• ${d.text}`).join('\n')||'无'}\n\n固定版本\n${meeting.materialVersionIds.join('\n')||'无'}\n\n来源 ${meeting.source}\n原文保留 ${meeting.transcript.length} 字；不会自动生成任务或改变现有任务状态。`;}
export class MeetingModal extends Modal {
  constructor(private host:KnowledgeHost,private existing?:Meeting,private initialProject?:string){super(host.app);}
  onOpen(){const c=this.contentEl;c.classList.add('elw-modal');const original=this.existing?JSON.parse(JSON.stringify(this.existing)) as Meeting:undefined;const recordId=original?.id||id('meeting');c.append(n('h2','',original?'会议记录':'新建会议'));
    const form=n('div','elw-form');const title=field(form,'主题',original?.title||'');const time=field(form,'时间',toLocalDateTimeInput(original?.startAt||new Date().toISOString()),'datetime-local');const project=pick(form,'项目',[{value:'',label:'选择项目'},...this.host.data.projects.map(p=>({value:p.id,label:p.name}))],original?.project||this.initialProject||this.host.data.projects[0]?.id||'');const participants=field(form,'参会人（逗号分隔）',original?.participants.join(', ')||'');const module=field(form,'模块（可选）',original?.module||'');const iteration=field(form,'迭代（可选）',original?.iteration||'');c.append(form);
    c.append(n('h3','','已确认决策'));const confirmed=field(c,'决策内容',original?.decisions.filter(d=>d.state==='confirmed').map(d=>d.text).join('\n')||'','textarea');confirmed.placeholder='每行一项，仅填写已明确确认的决定';
    const unresolved=field(c,'未决事项',original?.unresolved.join('\n')||'','textarea');
    c.append(n('h3','','行动项'));const actionsBox=n('div','elw-action-editor');c.append(actionsBox);const actionRows:{id:string;title:HTMLInputElement|HTMLTextAreaElement;task:HTMLSelectElement;owner:HTMLInputElement|HTMLTextAreaElement;due:HTMLInputElement|HTMLTextAreaElement;state:HTMLSelectElement;row:HTMLElement}[]=[];
    const addAction=(value?:MeetingAction)=>{const row=n('div','elw-action-form');const text=field(row,'行动',value?.text||'');const task=pick(row,'关联任务',[{value:'',label:'尚未关联'},...this.host.data.tasks.map(t=>({value:t.id,label:`${t.id} · ${t.title}`}))],value?.taskId||'');const owner=field(row,'负责人',value?.owner||'');const due=field(row,'截止日',value?.due||'','date');const state=pick(row,'行动状态',[{value:'open',label:'待办'},{value:'done',label:'已完成'}],value?.state||'open');const entry={id:value?.id||id('action'),title:text,task,owner,due,state,row};actionRows.push(entry);const sync=()=>{const linked=this.host.data.tasks.find(t=>t.id===task.value);owner.disabled=due.disabled=!!linked;if(linked){owner.value=linked.executor;due.value=linked.forecastDue;}};task.addEventListener('change',sync);sync();b(row,'移除此行',()=>{const index=actionRows.indexOf(entry);if(index>=0)actionRows.splice(index,1);row.remove();});actionsBox.append(row);};original?.actions.forEach(addAction);b(c,'+ 行动项',()=>addAction());
    const getVersions=checkList(c,'依据版本',(this.host.data.materialVersions||[]).map(v=>({value:v.id,label:`${v.title} · ${v.version} · ${v.id}`})),original?.materialVersionIds);
    const discussionSection=section(c,'讨论 / 建议');const discussion=field(discussionSection,'讨论（未确认）',original?.decisions.filter(d=>d.state==='discussion').map(d=>d.text).join('\n')||'','textarea');const suggestions=field(discussionSection,'建议（未确认）',original?.decisions.filter(d=>d.state==='suggestion').map(d=>d.text).join('\n')||'','textarea');
    const sources=section(c,'录音 / 原文');const source=field(sources,'来源',original?.source||'手动整理会议纪要');const recording=field(sources,'录音链接',original?.recordingUrl||'');const transcriptUrl=field(sources,'原文链接',original?.transcriptUrl||'');const transcript=field(sources,'原文',original?.transcript||'','textarea');const file=n('input');file.type='file';file.accept='.txt,.md';file.setAttribute('aria-label','导入纪要原文');file.addEventListener('change',()=>{const selected=file.files?.[0];if(!selected)return;if(selected.size>500_000){new Notice('原文最多 500KB');return;}void selected.text().then(text=>{transcript.value=text;new Notice('已读入原文，请整理上方决策与行动；未自动确认内容');});});sources.append(file);if(original?.recordingUrl)b(sources,'打开录音链接',()=>new KnowledgeConfirmModal(this.app,'打开录音链接',validateExternalUrl(original.recordingUrl!),'打开链接',async()=>openExternalUrl(this.app,original.recordingUrl!)).open());if(original?.transcriptUrl)b(sources,'打开原文链接',()=>new KnowledgeConfirmModal(this.app,'打开原文链接',validateExternalUrl(original.transcriptUrl!),'打开链接',async()=>openExternalUrl(this.app,original.transcriptUrl!)).open());
    const error=n('div','elw-error');error.setAttribute('role','alert');c.append(error);const footer=n('div','elw-modal-actions');if(original?.path)b(footer,'原始记录',()=>this.host.openFile(original.path));b(footer,'取消',()=>this.close());b(footer,'预览',()=>{try{
      const optional=(value:string)=>value.trim()||undefined;const candidate:Meeting={id:recordId,title:title.value.trim(),startAt:localDateTimeToISO(time.value),project:project.value,participants:participants.value.split(/[,，]/).map(v=>v.trim()).filter(Boolean),module:optional(module.value),iteration:optional(iteration.value),decisions:[...lines(confirmed.value).map(text=>({id:id('decision'),text,state:'confirmed' as const,source:source.value.trim()})),...lines(discussion.value).map(text=>({id:id('discussion'),text,state:'discussion' as const,source:source.value.trim()})),...lines(suggestions.value).map(text=>({id:id('suggestion'),text,state:'suggestion' as const,source:source.value.trim()}))],unresolved:lines(unresolved.value),actions:actionRows.map(row=>({id:row.id,text:row.title.value.trim(),taskId:optional(row.task.value),owner:optional(row.owner.value),due:optional(row.due.value),state:row.state.value as 'open'|'done'})),materialVersionIds:getVersions(),recordingUrl:recording.value.trim()?validateExternalUrl(recording.value):undefined,transcriptUrl:transcriptUrl.value.trim()?validateExternalUrl(transcriptUrl.value):undefined,transcript:transcript.value,source:source.value.trim(),lastUpdated:new Date().toISOString()};
      if(candidate.transcript.length>500_000)throw new Error('原文最多 500KB');const errors=validateMeeting(candidate);if(errors.length)throw new Error(errors.join('\n'));const reviewedTasks=new Map(candidate.actions.filter(x=>x.taskId).map(x=>{const task=this.host.data.tasks.find(t=>t.id===x.taskId);if(!task)throw new Error(`找不到任务 ${x.taskId}`);return [task.id,{executors:JSON.stringify(taskExecutors(task)),forecastDue:task.forecastDue}];}));const refs=new Set((this.host.data.materialVersions||[]).map(v=>v.id));if(candidate.materialVersionIds.some(version=>!refs.has(version)))throw new Error('有资料版本缺失，请刷新');
      new KnowledgeConfirmModal(this.app,'确认会议',meetingText(candidate,this.host.data),'保存会议',async()=>{await this.host.reload();for(const [taskId,old]of reviewedTasks){const task=this.host.data.tasks.find(t=>t.id===taskId);if(!task||JSON.stringify(taskExecutors(task))!==old.executors||task.forecastDue!==old.forecastDue)throw new Error(`任务 ${taskId} 的负责人或日期已变化，请重新预览`);}if(candidate.materialVersionIds.some(version=>!this.host.data.materialVersions?.some(v=>v.id===version)))throw new Error('依据版本已缺失，请重新预览');if(original)await this.host.store.updateMeeting(original,candidate);else await this.host.store.create('meeting',candidate);await this.host.reload();this.close();new Notice('会议已保存');}).open();
    }catch(e){error.textContent=message(e);}},true);c.append(footer);
  }
  onClose(){this.contentEl.replaceChildren();}
}
export class MaterialModal extends Modal {
  constructor(private host:KnowledgeHost,private previous?:MaterialVersion,private initialProject?:string){super(host.app);}
  onOpen(){const c=this.contentEl;c.classList.add('elw-modal');const versionId=id('version'),materialId=this.previous?.materialId||id('material');c.append(n('h2','',this.previous?'新增版本':'新增资料'));const form=n('div','elw-form');const title=field(form,'名称',this.previous?.title||'');const project=pick(form,'项目',this.host.data.projects.map(p=>({value:p.id,label:p.name})),this.previous?.project||this.initialProject||this.host.data.projects[0]?.id||'');const kind=pick(form,'类型',[{value:'document',label:'文档'},{value:'prototype',label:'原型'}],this.previous?.kind||'document');const version=field(form,'版本',this.previous?'':'v1');const module=field(form,'模块（可选）',this.previous?.module||'');const iteration=field(form,'迭代（可选）',this.previous?.iteration||'');const provider=field(form,'提供方',this.previous?.provider||'');const source=field(form,'来源',this.previous?.source||'手动录入');c.append(form);
    const mode=pick(c,'录入方式',[{value:'url',label:'在线链接'},{value:'file',label:'单个文件 / HTML'},{value:'folder',label:'原型文件夹'},{value:'zip',label:'原型 ZIP'}],'url');const inputs=n('div','elw-form');const url=field(inputs,'链接','');const file=n('input');file.type='file';file.setAttribute('aria-label','选择资料文件');inputs.append(file);const entry=pick(inputs,'HTML 入口',[{value:'',label:'请选择入口'}]);c.append(inputs);let plan:PrototypePlan|undefined,original:{name:string;bytes:Uint8Array}|undefined;let generation=0;const loaded=n('p','elw-modal-hint');c.append(loaded);
    const configure=()=>{generation++;plan=undefined;original=undefined;file.value='';loaded.textContent='';url.disabled=mode.value!=='url';file.disabled=mode.value==='url';file.multiple=mode.value==='folder';if(mode.value==='folder')file.setAttribute('webkitdirectory','');else file.removeAttribute('webkitdirectory');file.accept=mode.value==='zip'?'.zip':mode.value==='folder'?'':kind.value==='prototype'?'.html,.htm':'.pdf,.md,.txt,.docx,.pptx,.xlsx,.csv,.json';entry.replaceChildren();const choose=n('option','','请选择入口');choose.value='';entry.append(choose);entry.disabled=kind.value!=='prototype'||mode.value==='url';};mode.addEventListener('change',configure);kind.addEventListener('change',configure);configure();
    const error=n('div','elw-error');error.setAttribute('role','alert');
    file.addEventListener('change',()=>{const current=++generation;plan=undefined;original=undefined;loaded.textContent='读取中…';error.textContent='';const selected=Array.from(file.files||[]);void(async()=>{try{if(!selected.length){loaded.textContent='';return;}if(selected.length>500||selected.some(item=>item.size>10*1024*1024&&mode.value!=='zip')||selected.reduce((sum,item)=>sum+item.size,0)>50*1024*1024)throw new Error('文件最多 500 个、总计 50MB');let next:PrototypePlan,raw:{name:string;bytes:Uint8Array}|undefined;
      if(mode.value==='zip'){const item=selected[0];if(item.size>20*1024*1024)throw new Error('ZIP 压缩包最多 20MB');const bytes=new Uint8Array(await item.arrayBuffer());next=previewPrototypeZip(bytes);raw={name:item.name,bytes};}
      else{const files=await Promise.all(selected.map(async item=>({path:mode.value==='folder'?(item.webkitRelativePath||item.name):item.name,bytes:new Uint8Array(await item.arrayBuffer())})));next=inspectPrototypeFiles(files);}
      if(current!==generation)return;plan=next;original=raw;entry.replaceChildren();const choose=n('option','','请选择入口');choose.value='';entry.append(choose);for(const path of next.entryCandidates){const option=n('option','',path);option.value=path;entry.append(option);}loaded.textContent=`${next.files.length} 个文件 · ${(next.totalBytes/1024).toFixed(1)}KB${next.warnings.length?' · 请检查导入提醒':''}`;
    }catch(e){if(current===generation){error.textContent=message(e);loaded.textContent='';}}})();});
    const summary=field(c,'摘要','','textarea'),changeNotes=field(c,'变更说明','','textarea');const checks=section(c,'运行条件 / 评审');const network=pick(checks,'需要联网',[{value:'unknown',label:'未知'},{value:'true',label:'是'},{value:'false',label:'否'}],'unknown'),login=pick(checks,'需要登录',[{value:'unknown',label:'未知'},{value:'true',label:'是'},{value:'false',label:'否'}],'unknown'),requirements=field(checks,'运行要求','','textarea'),previewStatus=pick(checks,'人工预览检查',[{value:'unknown',label:'未检查'},{value:'pass',label:'通过（人工记录）'},{value:'fail',label:'失败（人工记录）'}],'unknown'),previewNotes=field(checks,'检查说明','','textarea'),issues=field(checks,'评审问题（每行一项）','','textarea');c.append(error);const actions=n('div','elw-modal-actions');b(actions,'取消',()=>this.close());b(actions,'预览',()=>{try{
      if(!project.value)throw new Error('请先创建项目');if(mode.value!=='url'&&!plan)throw new Error('请选择文件并等待读取完成');if(kind.value==='document'&&['folder','zip'].includes(mode.value))throw new Error('文件夹和 ZIP 入口用于原型；文档请选择单个文件');
      const selectedEntry=plan&&kind.value==='prototype'?validateEntry(plan,entry.value):undefined;const now=new Date().toISOString(),bool=(value:string):boolean|'unknown'=>value==='unknown'?'unknown':value==='true';const candidate:MaterialVersion={id:versionId,materialId,title:title.value.trim(),kind:kind.value as 'document'|'prototype',version:version.value.trim(),project:project.value,module:module.value.trim()||undefined,iteration:iteration.value.trim()||undefined,status:'incoming',summary:summary.value.trim(),source:source.value.trim(),provider:provider.value.trim(),sourceUrl:mode.value==='url'?validateExternalUrl(url.value):undefined,requiresNetwork:bool(network.value),requiresLogin:bool(login.value),runRequirements:requirements.value.trim(),previewStatus:previewStatus.value as 'unknown'|'pass'|'fail',previewNotes:previewNotes.value.trim(),changeNotes:changeNotes.value.trim(),reviewIssues:lines(issues.value),createdAt:now,lastUpdated:now};
      // File source paths are created by the store; placeholders here are only for structural preview validation.
      const errors=validateMaterialVersion({...candidate,...(plan?{sourceFile:`pending/${plan.files[0].path}`}:{})});if(errors.length)throw new Error(errors.join('\n'));const capturedPlan=plan?inspectPrototypeFiles(plan.files,plan.directories):undefined,capturedOriginal=original?{name:original.name,bytes:original.bytes.slice()}:undefined;
      const text=`${candidate.title} · ${candidate.version}\n${candidate.kind==='prototype'?'原型':'文档'} · 项目 ${candidate.project}\n提供方 ${candidate.provider}\n来源 ${candidate.source}\n${candidate.sourceUrl||`入口 ${selectedEntry||'原文件'}`}\n\n${candidate.summary}\n\n${capturedPlan?capturedPlan.files.map(f=>`${f.path} (${f.bytes.byteLength}B)`).join('\n'):''}\n${capturedPlan?.warnings.join('\n')||''}\n\n检查：${candidate.previewStatus}（人工记录）\n${candidate.previewNotes||''}\n\n只保存新版本，不自动采纳，不修改现有任务 / 会议引用。`;
      new KnowledgeConfirmModal(this.app,'确认资料版本',text,'保存新版本',async()=>{await this.host.store.createMaterial(candidate,capturedPlan,capturedOriginal,selectedEntry);await this.host.reload();this.close();new Notice('新版本已保存，尚未采纳');}).open();
    }catch(e){error.textContent=message(e);}},true);c.append(actions);
  }
  onClose(){this.contentEl.replaceChildren();}
}

export function openExternalUrl(app:App,value:string){const url=validateExternalUrl(value);if(Platform.isDesktopApp){const requireFn=(window as unknown as {require?:(id:string)=>{shell:{openExternal:(url:string)=>Promise<void>}}}).require;if(requireFn){void requireFn('electron').shell.openExternal(url).catch(e=>new Notice(message(e)));return;}}window.open(url,'_blank','noopener,noreferrer');}
export function openMaterialSource(host:KnowledgeHost,version:MaterialVersion){void(async()=>{
  await host.store.verifyMaterialAssets(version);
  if(version.sourceUrl){const safe=validateExternalUrl(version.sourceUrl);new KnowledgeConfirmModal(host.app,'在外部浏览器打开',`${safe}\n\n联网：${String(version.requiresNetwork)} · 登录：${String(version.requiresLogin)}\n${version.runRequirements||''}\n在线内容由提供方维护；工作台不会运行脚本。`,'打开链接',async()=>{await host.store.verifyMaterialAssets(version);openExternalUrl(host.app,safe);}).open();return;}
  const path=version.kind==='prototype'?version.entryPath:version.sourceFile;if(!path)throw new Error('未记录可打开的入口');const safe=validateRelativePath(path);
  if(version.kind==='prototype'&&!/\.html?$/i.test(safe))throw new Error('原型入口必须为 HTML');
  if(version.kind==='document'&&!/\.(pdf|md|txt|docx|pptx|xlsx|csv|json)$/i.test(safe))throw new Error('该文件类型不支持从工作台直接打开');
  if(!Platform.isDesktopApp||!(host.app.vault.adapter instanceof FileSystemAdapter)){new Notice('本地文件的外部打开仅支持桌面版；文件已保存在 Vault，可通过系统文件管理器打开');return;}
  new KnowledgeConfirmModal(host.app,'在默认外部应用打开',`${safe}\n\n联网：${String(version.requiresNetwork)} · 登录：${String(version.requiresLogin)}\n${version.runRequirements||''}\nHTML 可能运行脚本，只打开可信文件。`,'打开文件',async()=>{
    await host.store.verifyMaterialAssets(version);
    const adapter=host.app.vault.adapter as FileSystemAdapter;
    const requireFn=(window as unknown as {require?:(name:string)=>unknown}).require;if(!requireFn)throw new Error('当前环境不支持系统外部打开');
    const fs=requireFn('node:fs') as {promises:{realpath(path:string):Promise<string>}};
    const paths=requireFn('node:path') as {sep:string;relative(from:string,to:string):string;isAbsolute(path:string):boolean};
    const vaultRoot=await fs.promises.realpath(adapter.getBasePath()),full=await fs.promises.realpath(adapter.getFullPath(safe));
    const relative=paths.relative(vaultRoot,full);
    if(relative.startsWith(`..${paths.sep}`)||relative==='..'||paths.isAbsolute(relative))throw new Error('入口实际路径超出 Vault，未打开');
    const expected=adapter.getFullPath(safe),resolvedParent=await fs.promises.realpath(adapter.getFullPath(host.store.assetRoot(version.id)));
    const inside=paths.relative(resolvedParent,full);if(inside.startsWith(`..${paths.sep}`)||inside==='..'||paths.isAbsolute(inside))throw new Error('入口链接指向其他版本目录，未打开');
    if(full!==expected.replace(/[/\\]+/g,paths.sep)&&full!==adapter.getFullPath(safe))throw new Error('入口包含符号链接或路径别名，请在系统中检查后重新导入');
    const shell=(requireFn('electron') as {shell:{openPath(path:string):Promise<string>}}).shell;
    const result=await shell.openPath(full);if(result)throw new Error(result);
  }).open();
})().catch(error=>new Notice(message(error)));}

export class MaterialDetailsModal extends Modal {
  constructor(private host:KnowledgeHost,private version:MaterialVersion){super(host.app);}
  onOpen(){const c=this.contentEl,v=this.version;c.classList.add('elw-modal');c.append(n('h2','',`${v.title} · ${v.version}`));const adopted=getAdoptedVersion(this.host.data,v.materialId,v.project),adoptionToken=getLatestAdoption(this.host.data,v.materialId,v.project)?.id??null;c.append(n('p','elw-modal-hint',`${adopted?.id===v.id?'已采纳':'未采纳'} · ${v.kind==='prototype'?'原型':'文档'} · ${v.lastUpdated.slice(0,10)}`));if(v.summary)c.append(n('p','',v.summary));const actions=n('div','elw-modal-actions');b(actions,'打开',()=>openMaterialSource(this.host,v));b(actions,'新增版本',()=>{this.close();new MaterialModal(this.host,v).open();});const adopt=b(actions,'采纳此版本',()=>{new KnowledgeConfirmModal(this.app,'确认采纳',`${v.title} · ${v.version}\n原采纳版本：${adopted?.version||'无'}\n\n不会改写任何任务 / 会议的固定版本引用。`,'采纳',async()=>{await this.host.store.adopt(v,adoptionToken);await this.host.reload();this.close();new Notice('已记录采纳决定');}).open();},true);adopt.disabled=adopted?.id===v.id;c.append(actions);
    if(v.changeNotes){c.append(n('h3','','变更'),n('p','',v.changeNotes));}if(v.reviewIssues.length){c.append(n('h3','','评审问题'));v.reviewIssues.forEach(issue=>c.append(n('p','',`• ${issue}`)));}
    c.append(n('h3','','运行条件'),n('p','',`联网：${v.requiresNetwork==='unknown'?'未知':v.requiresNetwork?'需要':'不需要'} · 登录：${v.requiresLogin==='unknown'?'未知':v.requiresLogin?'需要':'不需要'}`),n('p','',v.runRequirements||'未说明'),n('p','',`人工检查：${{unknown:'未检查',pass:'通过',fail:'失败'}[v.previewStatus]}${v.previewNotes?` · ${v.previewNotes}`:''}`));
    c.append(n('h3','','版本历史'));for(const item of (this.host.data.materialVersions||[]).filter(x=>x.materialId===v.materialId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))){b(c,`${item.version} · ${item.createdAt.slice(0,10)}${adopted?.id===item.id?' · 已采纳':''}`,()=>{this.close();new MaterialDetailsModal(this.host,item).open();});}
    c.append(n('h3','','引用此版本'));const tasks=this.host.data.tasks.filter(t=>t.materialVersionIds?.includes(v.id));const meetings=(this.host.data.meetings||[]).filter(m=>m.materialVersionIds.includes(v.id));if(!tasks.length&&!meetings.length)c.append(n('p','','暂无引用'));tasks.forEach(task=>b(c,`任务 · ${task.title}`,()=>{this.close();this.host.openTask(task);}));meetings.forEach(meeting=>b(c,`会议 · ${meeting.title}`,()=>{this.close();new MeetingModal(this.host,meeting).open();}));
    const source=n('details','elw-form-section');source.append(n('summary','','来源 / 文件'));source.append(n('div','elw-preview',`版本 ID：${v.id}\n资料 ID：${v.materialId}\n提供方：${v.provider}\n来源：${v.source}\n${v.sourceUrl||v.sourceFile||''}\n入口：${v.entryPath||'无'}\n${v.files?.map(f=>`${f.path} · ${f.size}B`).join('\n')||''}`));if(v.path)b(source,'原始记录',()=>this.host.openFile(v.path));c.append(source);b(c,'关闭',()=>this.close());
  }
  onClose(){this.contentEl.replaceChildren();}
}
export function appendTaskTrace(parent:HTMLElement,host:KnowledgeHost,task:Task){const trace=taskTrace(host.data,task);const box=n('details','elw-form-section');box.append(n('summary','','依据 / 来源'));box.append(n('p','',`执行人：${taskExecutors(task).map(id=>id||'未分配').join('、')||'未分配'}`));for(const v of trace.materialVersions)b(box,`${v.title} · ${v.version}`,()=>new MaterialDetailsModal(host,v).open());for(const m of trace.meetings)b(box,`会议 · ${m.title}`,()=>new MeetingModal(host,m).open());trace.warnings.forEach(w=>box.append(n('p','elw-error',w)));if(!trace.materialVersions.length&&!trace.meetings.length)box.append(n('p','','未关联会议或资料版本'));parent.append(box);}

export function taskReferenceEditor(parent:HTMLElement,host:KnowledgeHost,task?:Task){
 const meetings=(host.data.meetings||[]).map(m=>({value:m.id,label:`${m.title} · ${formatLocalDateTime(m.startAt)} · ${m.id}`}));for(const missing of task?.meetingIds||[])if(!meetings.some(m=>m.value===missing))meetings.push({value:missing,label:`缺失会议 ${missing}`});
 const versions=(host.data.materialVersions||[]).map(v=>({value:v.id,label:`${v.title} · ${v.version} · ${v.id}`}));for(const missing of task?.materialVersionIds||[])if(!versions.some(v=>v.value===missing))versions.push({value:missing,label:`缺失版本 ${missing}`});
 const getMeetings=checkList(parent,'会议依据',meetings,task?.meetingIds),getVersions=checkList(parent,'固定资料版本',versions,task?.materialVersionIds);
 return ()=>({meetingIds:getMeetings(),materialVersionIds:getVersions()});
}
