import { MeetingModal, MaterialModal, MaterialDetailsModal, openMaterialSource, appendTaskTrace, taskReferenceEditor } from './knowledge-modals';
import type { ProjectTab } from './knowledge-ui';
import { App, ItemView, Modal, Notice, Plugin, PluginSettingTab, Setting, TFile, WorkspaceLeaf } from 'obsidian';
import { DEFAULT_SETTINGS, TASK_STATUSES, emptyWorkbenchData, generateBaseline, generateWeeklySummary, isValidDate, taskTouchesPeriod, type WorkbenchData, type WorkbenchSettings, type Task, type Period } from './domain';
import { applyApprovedUpdates, extractUpdateCandidates, previewImport } from './importer';
import { renderWorkbench, STATUS_LABEL, type UIState, type TabId } from './ui';
import { VaultStore, safeRoot } from './store';

const VIEW_TYPE = 'engineering-lead-workbench';
interface PluginSettings extends WorkbenchSettings { rootFolder: string }
const INITIAL_SETTINGS:PluginSettings={...DEFAULT_SETTINGS,calendar:{weekdays:[1,2,3,4,5],exceptions:{}},rootFolder:'Engineering Workbench'};
export function todayISO():string{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function weekPeriod(today=todayISO()):Period{const d=new Date(`${today}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));const start=d.toISOString().slice(0,10);d.setUTCDate(d.getUTCDate()+6);return {start,end:d.toISOString().slice(0,10)};}
function uid(prefix:string){return `${prefix}-${new Date().toISOString().replace(/[-:.TZ]/g,'')}-${Math.random().toString(36).slice(2,6)}`;}
function err(error:unknown){return error instanceof Error?error.message:String(error);}
function node<K extends keyof HTMLElementTagNameMap>(tag:K,cls='',text?:string):HTMLElementTagNameMap[K]{const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function button(parent:HTMLElement,label:string,fn:()=>void,primary=false){const b=node('button',primary?'mod-cta':'',label);b.type='button';b.addEventListener('click',fn);parent.append(b);return b;}

export default class EngineeringLeadWorkbench extends Plugin {
  settings:PluginSettings=INITIAL_SETTINGS;
  data:WorkbenchData=emptyWorkbenchData();
  store!:VaultStore;
  period=weekPeriod();
  private reloadTimer:number|undefined;
  private reloadVersion=0;
  async onload(){
    const saved=(await this.loadData()) as Partial<PluginSettings>|null;
    this.settings={...INITIAL_SETTINGS,...saved,calendar:{...INITIAL_SETTINGS.calendar,...saved?.calendar}};
    try{safeRoot(this.settings.rootFolder);}catch{this.settings.rootFolder=INITIAL_SETTINGS.rootFolder;new Notice('工作台数据目录无效，已使用默认目录');}
    if(!['dev-complete','test-passed','released','accepted'].includes(this.settings.closureStatus))this.settings.closureStatus='test-passed';
    if(!Number.isFinite(this.settings.staleDays)||this.settings.staleDays<1)this.settings.staleDays=7;
    this.store=new VaultStore(this.app,this.settings.rootFolder);
    this.registerView(VIEW_TYPE,leaf=>new WorkbenchView(leaf,this));
    this.addRibbonIcon('layout-dashboard','打开研发负责人工作台',()=>void this.openWorkbench());
    this.addCommand({id:'open-workbench',name:'打开研发负责人工作台',callback:()=>void this.openWorkbench()});
    this.addCommand({id:'import-tasks',name:'导入任务（CSV / JSON）',callback:()=>new ImportModal(this).open()});
    this.addCommand({id:'organize-progress',name:'整理本次进展（离线规则辅助）',callback:()=>new ProgressModal(this).open()});
    this.addCommand({id:'weekly-summary',name:'生成周会摘要',callback:()=>void this.summary()});
    this.addCommand({id:'new-meeting',name:'新建会议',callback:()=>new MeetingModal(this).open()});
    this.addCommand({id:'new-material-version',name:'新增资料版本',callback:()=>new MaterialModal(this).open()});
    this.addSettingTab(new WorkbenchSettingsTab(this.app,this));
    const refresh=()=>{window.clearTimeout(this.reloadTimer);this.reloadTimer=window.setTimeout(()=>void this.reload(),220);};
    this.registerEvent(this.app.vault.on('create',refresh));this.registerEvent(this.app.vault.on('modify',refresh));this.registerEvent(this.app.vault.on('delete',refresh));this.registerEvent(this.app.vault.on('rename',refresh));
    this.app.workspace.onLayoutReady(()=>void this.reload());
    await this.reload();
  }
  onunload(){window.clearTimeout(this.reloadTimer);this.app.workspace.detachLeavesOfType(VIEW_TYPE);}
  async reload(){const version=++this.reloadVersion;try{const data=await this.store.load();if(version!==this.reloadVersion)return;this.data=data;this.redraw();}catch(error){new Notice(`读取工作台失败：${err(error)}`);}}
  redraw(){for(const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE)){if(leaf.view instanceof WorkbenchView)leaf.view.render();}}
  async saveSettings(){await this.saveData(this.settings);this.store.setRoot(this.settings.rootFolder);await this.reload();}
  async openWorkbench(){let leaf=this.app.workspace.getLeavesOfType(VIEW_TYPE)[0];if(!leaf){leaf=this.app.workspace.getLeaf('tab');await leaf.setViewState({type:VIEW_TYPE,active:true});}await this.app.workspace.revealLeaf(leaf);}
  openTask(task:Task){new TaskModal(this,task).open();}
  openFile(path?:string){if(!path)return;const file=this.app.vault.getAbstractFileByPath(path);if(file instanceof TFile)void this.app.workspace.getLeaf('tab').openFile(file);else new Notice('记录已移动，请刷新后重试');}
  showSettings(){new Notice('打开 设置 → 第三方插件 → Engineering Lead Workbench，可配置目录、日历与闭环标准');}
  async summary(){await this.reload();const text=generateWeeklySummary(this.data,{period:this.period,today:todayISO(),...this.settings});new ConfirmModal(this.app,'周会摘要预览',text,'确认保存 Markdown',async()=>{const file=await this.store.saveReport(`周会摘要 ${this.period.start}`,text);this.openFile(file.path);new Notice('周会摘要已保存；未向外部发送');}).open();}
  async baseline(){await this.reload();const tasks=this.data.tasks.filter(t=>t.status!=='cancelled'&&taskTouchesPeriod(t,this.period));if(!tasks.length){new Notice('本周期没有计划任务，请先分配周期投入或预测日期');return;}const snapshot=generateBaseline(tasks,{id:uid('baseline'),name:`周计划 ${this.period.start}`,createdAt:new Date().toISOString(),period:this.period});new ConfirmModal(this.app,'冻结本周期基线',`周期 ${this.period.start} → ${this.period.end}\n\n${tasks.map(t=>`${t.id} · ${t.title}\n  原承诺 ${t.originalDue||'未排期'} / 当前预测 ${t.forecastDue||'未评估'} / ${STATUS_LABEL[t.status]}`).join('\n\n')}\n\n确认后将新增不可变的快照文件；工作台不会自动改写它。`,'确认冻结',async()=>{await this.store.createBaseline(snapshot);await this.reload();new Notice('基线已冻结；后续变化会单独显示');}).open();}
  createRecord(kind:'project'|'person'|'module'|'decision'){
    const defs={project:{id:uid('project'),name:'新项目',description:'',owner:'',targetDate:todayISO(),milestones:[],source:'手动创建'},person:{id:uid('person'),name:'新成员',source:'手动创建'},module:{id:uid('module'),name:'新模块',project:this.data.projects[0]?.id||'',owner:'',source:'手动创建'},decision:{id:uid('decision'),title:'新决策',date:todayISO(),owner:'',decision:'请填写已确认的决定及其依据',source:'手动创建',project:this.data.projects[0]?.id||''}};
    const labels={project:'项目',person:'人员',module:'模块',decision:'决策'};
    new ConfirmModal(this.app,`创建${labels[kind]}记录`,`将在当前工作台新增可编辑的 Markdown ${labels[kind]}模板。\n\n人员容量默认未知，请按真实日历填写 capacity.hoursPerDay 与各类扣减。模块 owner 为稳定负责人，任务 executor 为当前执行人。`,'创建并打开',async()=>{const file=await this.store.create(kind,defs[kind]);await this.reload();this.openFile(file.path);}).open();
  }
}

class WorkbenchView extends ItemView {
  tab:TabId='home';search='';project='';baselineId='';selectedProject='';projectTab:ProjectTab='overview';
  constructor(leaf:WorkspaceLeaf,private plugin:EngineeringLeadWorkbench){super(leaf);}
  getViewType(){return VIEW_TYPE;}getDisplayText(){return '研发负责人工作台';}getIcon(){return 'layout-dashboard';}
  async onOpen(){this.contentEl.style.padding='0';this.render();}async onClose(){this.contentEl.replaceChildren();}
  render(){const scroll=this.contentEl.querySelector('.elw-main')?.scrollTop||0;const s:UIState={data:this.plugin.data,settings:this.plugin.settings,period:this.plugin.period,today:todayISO(),tab:this.tab,search:this.search,project:this.project,warnings:this.plugin.store.warnings,baselineId:this.baselineId,selectedProject:this.selectedProject,projectTab:this.projectTab};renderWorkbench(this.contentEl,s,{projectDetail:id=>{this.selectedProject=id;this.projectTab='overview';this.render();},projectTab:tab=>{this.projectTab=tab;this.render();},meeting:meeting=>new MeetingModal(this.plugin,meeting).open(),createMeeting:project=>new MeetingModal(this.plugin,undefined,project).open(),material:version=>new MaterialDetailsModal(this.plugin,version).open(),createMaterial:project=>new MaterialModal(this.plugin,undefined,project).open(),openMaterial:version=>openMaterialSource(this.plugin,version),tab:id=>{this.tab=id;this.selectedProject='';this.render();},search:value=>{this.search=value;this.render();},project:value=>{this.project=value;this.render();},period:p=>{if(!isValidDate(p.start)||!isValidDate(p.end)||p.start>p.end){new Notice('请选择有效且开始不晚于结束的周期');this.render();return;}if((new Date(p.end).getTime()-new Date(p.start).getTime())/86400000>366){new Notice('观察周期最长 367 天');this.render();return;}this.plugin.period=p;this.baselineId='';this.render();},task:t=>new TaskModal(this.plugin,t).open(),open:path=>this.plugin.openFile(path),create:()=>new TaskModal(this.plugin).open(),createRecord:kind=>this.plugin.createRecord(kind),import:()=>new ImportModal(this.plugin).open(),progress:()=>new ProgressModal(this.plugin).open(),summary:()=>void this.plugin.summary(),baseline:()=>void this.plugin.baseline(),chooseBaseline:id=>{this.baselineId=id;this.render();},refresh:()=>void this.plugin.reload(),settings:()=>this.plugin.showSettings()});const main=this.contentEl.querySelector('.elw-main');if(main)main.scrollTop=scroll;}
}

class ConfirmModal extends Modal {
  constructor(app:App,private title:string,private preview:string,private confirmText:string,private apply:()=>Promise<void>){super(app);}
  onOpen(){this.contentEl.classList.add('elw-modal');this.contentEl.append(node('h2','',this.title));const pre=node('div','elw-preview',this.preview);this.contentEl.append(pre);const error=node('div','elw-error');error.setAttribute('role','alert');this.contentEl.append(error);const actions=node('div','elw-modal-actions');button(actions,'取消',()=>this.close());const save=button(actions,this.confirmText,()=>{save.disabled=true;void this.apply().then(()=>this.close()).catch(e=>{error.textContent=err(e);save.disabled=false;});},true);this.contentEl.append(actions);}
  onClose(){this.contentEl.replaceChildren();}
}

class TaskModal extends Modal {
  constructor(private plugin:EngineeringLeadWorkbench,private task?:Task){super(plugin.app);}
  onOpen(){const c=this.contentEl;c.classList.add('elw-modal');c.append(node('h2','',this.task?'更新共享任务':'新建共享任务'),node('p','elw-modal-hint','确认后只更新该任务的属性，正文与自定义属性保留。原始日期创建后不由工作台覆盖。'));
    const fields:Record<string,HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>={};const form=node('div','elw-form');
    const add=(key:string,label:string,value:string,type='text',wide=false)=>{const row=node('label',wide?'wide':'',label);let input:HTMLInputElement|HTMLTextAreaElement;if(type==='textarea')input=node('textarea');else{input=node('input');input.type=type;}input.value=value;input.setAttribute('aria-label',label);row.append(input);form.append(row);fields[key]=input;return input;};
    const t=this.task;add('id','任务 ID',t?.id||uid('task')).disabled=!!t;add('title','任务标题',t?.title||'');add('project','项目 ID',t?.project||this.plugin.data.projects[0]?.id||'');add('module','模块 ID',t?.module||'');add('executor','当前执行人 ID',t?.executor||'');add('executors','共同执行人 ID（逗号分隔）',t?.executors?.join(', ')||'');const statusRow=node('label','','状态');const status=node('select');TASK_STATUSES.forEach(s=>{const o=node('option','',STATUS_LABEL[s]);o.value=s;status.append(o)});status.value=t?.status||'planned';fields.status=status;statusRow.append(status);form.append(statusRow);
    add('originalStart','原始开始日期',t?.originalStart||'','date').disabled=!!t;add('originalDue','原始承诺日期',t?.originalDue||'','date').disabled=!!t;add('forecastDue','当前预测日期（条件成立时）',t?.forecastDue||'','date');const remaining=add('remainingHours','剩余工作量（小时）',t?.remainingHours==null?'':String(t.remainingHours),'number');(remaining as HTMLInputElement).min='0';(remaining as HTMLInputElement).step='0.5';add('dependencies','依赖任务 ID（逗号分隔）',t?.dependencies.join(', ')||'');add('source','来源（单据、会议或原始记录）',t?.source||'手动录入');add('nextAction','下一步可执行动作',t?.nextAction||'','textarea',true);add('blocker','阻塞事实',t?.blocker||'');add('risk','风险判断（未验证的判断）',t?.risk||'');add('contact','跟进 / 对接人',t?.contact||'');add('coordinationDue','跟进到期日',t?.coordinationDue||'','date');add('allocations','周期投入 allocations（小时，不是全部积压）',JSON.stringify(t?.allocations||[],null,2),'textarea',true);c.append(form);
    const references=taskReferenceEditor(c,this.plugin,t);
    if(t&&this.plugin.data.decisions)appendTaskTrace(c,this.plugin,t);
    if(t){const evidence=node('details');evidence.append(node('summary','','事实 / 预测 / 判断与来源'));for(const [key,label]of [['facts','事实'],['forecasts','预测'],['judgments','判断']] as const){for(const item of t[key]||[]){const box=node('div','elw-evidence');box.append(node('strong','',label),node('p','',item.text),node('small','',`${item.source} · ${item.recordedAt}`));evidence.append(box);}}evidence.append(node('p','elw-unchanged',`任务来源 ${t.source} · 最后更新 ${t.lastUpdated}`));c.append(evidence);}
    const error=node('div','elw-error');error.setAttribute('role','alert');c.append(error);const actions=node('div','elw-modal-actions');if(t?.path)button(actions,'打开原始 Markdown',()=>{this.plugin.openFile(t.path);this.close();});button(actions,'取消',()=>this.close());const save=button(actions,t?'确认更新共享记录':'确认创建任务',()=>{void(async()=>{save.disabled=true;error.textContent='';try{const raw:Record<string,unknown>={...t};Object.entries(fields).forEach(([key,input])=>raw[key]=input.value);raw.remainingHours=fields.remainingHours.value;raw.executors=fields.executors.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean);if(!t?.executors&&!(raw.executors as string[]).length)delete raw.executors;raw.dependencies=fields.dependencies.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean);raw.allocations=JSON.parse(fields.allocations.value);Object.assign(raw,references());raw.lastUpdated=new Date().toISOString();if(!raw.coordinationDue)delete raw.coordinationDue;const result=previewImport(JSON.stringify([raw]),'json',[]);if(result.errors.length||!result.tasks.length)throw new Error(result.errors.map(x=>`${x.field}: ${x.message}`).join('\n')||'任务无效');const value=result.tasks[0];if(t){const changes:Partial<Task>={...value};for(const key of ['blocker','risk','contact','coordinationDue'] as const)if(!fields[key].value.trim())changes[key]=undefined;await this.plugin.store.updateTask(t,changes);}else await this.plugin.store.create('task',value);await this.plugin.reload();this.close();new Notice(t?'任务已更新':'任务已创建');}catch(e){error.textContent=err(e);save.disabled=false;}})();},true);c.append(actions);
  }
  onClose(){this.contentEl.replaceChildren();}
}

class ImportModal extends Modal {
  constructor(private plugin:EngineeringLeadWorkbench){super(plugin.app);}
  onOpen(){const c=this.contentEl;c.classList.add('elw-modal');c.append(node('h2','','导入任务 · 先预览，再确认'),node('p','elw-modal-hint','粘贴 CSV / JSON 或选择本地导出文件。此操作不会连接 TAPD / WBS；现有 ID 不会被静默覆盖。导入存在错误时无法写入。'));
    const format=node('select');format.setAttribute('aria-label','导入格式');for(const id of ['csv','json']){const o=node('option','',id.toUpperCase());o.value=id;format.append(o);}const file=node('input');file.type='file';file.accept='.csv,.json,text/csv,application/json';file.setAttribute('aria-label','选择 CSV 或 JSON 文件');const input=node('textarea','elw-paste');input.placeholder='id,title,project,module,executor,status,originalStart,originalDue,forecastDue,remainingHours,allocations,dependencies,nextAction,source,lastUpdated';input.setAttribute('aria-label','导入内容');file.addEventListener('change',()=>{const selected=file.files?.[0];if(!selected)return;if(selected.size>2_000_000){new Notice('请将导出文件拆分为小于 2MB 的批次');return;}format.value=selected.name.toLowerCase().endsWith('.json')?'json':'csv';void selected.text().then(text=>{input.value=text;invalidate();});});c.append(format,file,input);const preview=node('div','elw-preview');preview.hidden=true;const error=node('div','elw-error');error.setAttribute('role','alert');c.append(preview,error);const actions=node('div','elw-modal-actions');button(actions,'取消',()=>this.close());button(actions,'校验并预览',()=>{error.textContent='';try{if(input.value.length>2_000_000)throw new Error('单批内容不能超过 2MB');const reviewedText=input.value,reviewedFormat=format.value as 'csv'|'json';const result=previewImport(reviewedText,reviewedFormat,this.plugin.data.tasks);preview.hidden=false;preview.textContent=`可新增 ${result.tasks.length} 条 · 跳过重复 ${result.duplicates.length} 条 · 错误 ${result.errors.length} 条\n\n${result.tasks.map(t=>`${t.id} · ${t.title} · ${STATUS_LABEL[t.status]} · ${t.source}`).join('\n')}\n\n${result.duplicates.map(d=>`重复 行 ${d.row} / ${d.id}: ${d.reason}`).join('\n')}\n${result.warnings.map(w=>`提醒 行 ${w.row} / ${w.field}: ${w.message}`).join('\n')}\n${result.errors.map(e=>`错误 行 ${e.row} / ${e.field}: ${e.message}`).join('\n')}`;save.disabled=!result.canApply||!result.tasks.length;save.onclick=()=>{save.disabled=true;input.disabled=true;format.disabled=true;file.disabled=true;void(async()=>{let count=0;try{await this.plugin.reload();const fresh=previewImport(reviewedText,reviewedFormat,this.plugin.data.tasks);if(!fresh.canApply)throw new Error('数据自预览后发生变化，请重新校验');for(const task of fresh.tasks){await this.plugin.store.create('task',task);count++;}await this.plugin.reload();new Notice(`已新增 ${count} 条任务，未覆盖原记录`);this.close();}catch(e){error.textContent=`已写入 ${count} 条。${err(e)}；可重新预览，已成功的记录会去重。`;input.disabled=false;format.disabled=false;file.disabled=false;await this.plugin.reload();}})();};}catch(e){error.textContent=err(e);save.disabled=true;}});const save=button(actions,'确认导入新增记录',()=>{},true);save.disabled=true;const invalidate=()=>{save.disabled=true;preview.hidden=true;};input.addEventListener('input',invalidate);format.addEventListener('change',invalidate);file.addEventListener('change',invalidate);c.append(actions);
  }
  onClose(){this.contentEl.replaceChildren();}
}

class ProgressModal extends Modal {
  constructor(private plugin:EngineeringLeadWorkbench){super(plugin.app);}
  onOpen(){const c=this.contentEl;c.classList.add('elw-modal');c.append(node('h2','','整理本次进展'),node('p','elw-modal-hint','离线规则辅助，不是大模型。每行写明任务 ID 与明确字段，例如：TASK-1 状态: 测试通过；TASK-2 预测日期: 2026-10-09。只生成建议，勾选并确认后才写入。'));
    const input=node('textarea','elw-paste');input.setAttribute('aria-label','本次进展原文');input.placeholder='任务ID 状态: 测试通过\n任务ID 下一步: 安排验收\n未匹配的内容可在确认后存入收件箱';c.append(input);const review=node('div');c.append(review);const error=node('div','elw-error');error.setAttribute('role','alert');c.append(error);const actions=node('div','elw-modal-actions');button(actions,'取消',()=>this.close());button(actions,'生成待确认建议',()=>{error.textContent='';review.replaceChildren();if(input.value.length>100_000){error.textContent='请将进展分为小于 100KB 的批次';return;}const reviewedText=input.value;const reviewedTasks=JSON.parse(JSON.stringify(this.plugin.data.tasks)) as Task[];const result=extractUpdateCandidates(reviewedText,reviewedTasks);const selected=new Set<string>();review.append(node('p','elw-modal-hint',`提取 ${result.candidates.length} 条建议。默认均未选中，请核实原文、来源与字段含义。`));result.candidates.forEach(candidate=>{const row=node('div','elw-review-item');const label=node('label');const cb=node('input');cb.type='checkbox';cb.addEventListener('change',()=>{if(cb.checked)selected.add(candidate.id);else selected.delete(candidate.id);});label.append(cb,node('span','',`${candidate.taskId} · ${candidate.field}: ${String(candidate.previousValue??'空')} → ${String(candidate.proposedValue)}`));row.append(label,node('small','',`原文：${candidate.evidence}\n规则依据：${candidate.reason}`));review.append(row);});result.warnings.forEach(w=>review.append(node('p','elw-modal-hint',w)));const inboxLabel=node('label','elw-review-item');const inbox=node('input');inbox.type='checkbox';inbox.style.width='auto';inboxLabel.append(inbox,node('span','','将本次原文另存到待确认收件箱（不计入事实和完成率）'));review.append(inboxLabel);const save=button(review,'确认写入所选建议',()=>{save.disabled=true;input.disabled=true;const completedIds:string[]=[];void(async()=>{try{const approved=result.candidates.filter(x=>selected.has(x.id));if(!approved.length&&!inbox.checked)throw new Error('请勾选建议或选择保存收件箱');const originalTasks=reviewedTasks;const updated=applyApprovedUpdates(originalTasks,approved,{updatedAt:new Date().toISOString(),source:'手动确认的进展原文'});const changedIds=new Set(approved.map(x=>x.taskId));let count=0;for(const task of updated){if(changedIds.has(task.id)){const original=originalTasks.find(x=>x.id===task.id);if(original)await this.plugin.store.preflightTask(original,task);}}for(const task of updated){if(changedIds.has(task.id)){const original=originalTasks.find(x=>x.id===task.id);if(original){await this.plugin.store.updateTask(original,task);completedIds.push(task.id);count++;}}}if(inbox.checked)await this.plugin.store.writeInbox(reviewedText);await this.plugin.reload();new Notice(`已确认更新 ${count} 条任务${inbox.checked?'，原文已存入收件箱':''}`);this.close();}catch(e){error.textContent=`已更新 ${completedIds.length} 条${completedIds.length?`（${completedIds.join('、')}）`:''}。${err(e)}。请重新生成建议后再确认。`;input.disabled=false;review.replaceChildren();await this.plugin.reload();}})();},true);});input.addEventListener('input',()=>review.replaceChildren());c.append(actions);
  }
  onClose(){this.contentEl.replaceChildren();}
}

class WorkbenchSettingsTab extends PluginSettingTab {
  constructor(app:App,private plugin:EngineeringLeadWorkbench){super(app,plugin);}
  display(){const c=this.containerEl;c.replaceChildren();c.classList.add('elw-settings');c.append(node('h2','','研发负责人工作台'),node('p','','本地 Markdown 为唯一数据源。变更目录不会移动或删除现有记录。'));
    new Setting(c).setName('数据目录').setDesc('Vault 内的普通文件夹。更改后读取新目录，原文件不动。').addText(t=>t.setValue(this.plugin.settings.rootFolder).onChange(value=>{try{safeRoot(value);t.inputEl.setCustomValidity('');}catch(e){t.inputEl.setCustomValidity(err(e));}}).inputEl.addEventListener('blur',e=>{const value=(e.target as HTMLInputElement).value;try{this.plugin.settings.rootFolder=safeRoot(value);void this.plugin.saveSettings();}catch(error){new Notice(err(error));}}));
    new Setting(c).setName('默认闭环标准').setDesc('开发完成、测试通过、发布与验收保留独立状态；默认测试通过。').addDropdown(d=>{for(const status of ['dev-complete','test-passed','released','accepted'])d.addOption(status,STATUS_LABEL[status]);d.setValue(this.plugin.settings.closureStatus).onChange(async value=>{this.plugin.settings.closureStatus=value as WorkbenchSettings['closureStatus'];await this.plugin.saveSettings();});});
    new Setting(c).setName('未更新提醒（天）').addText(t=>t.setValue(String(this.plugin.settings.staleDays)).onChange(async value=>{const n=Number(value);if(Number.isInteger(n)&&n>=1&&n<=365){this.plugin.settings.staleDays=n;await this.plugin.saveSettings();}}));
    c.append(node('h3','','实际工作日历'),node('p','','0=周日，1=周一，…，6=周六；exceptions 中 true 为调休工作日、false 为假日。人员可在自己的 Markdown 记录里覆盖此日历。'));
    const calendar=node('textarea');calendar.value=JSON.stringify(this.plugin.settings.calendar,null,2);calendar.setAttribute('aria-label','工作日历 JSON');c.append(calendar);button(c,'校验并保存日历',()=>{try{const value=JSON.parse(calendar.value) as WorkbenchSettings['calendar'];if(!Array.isArray(value.weekdays)||value.weekdays.some(n=>!Number.isInteger(n)||n<0||n>6)||new Set(value.weekdays).size!==value.weekdays.length)throw new Error('weekdays 必须是 0–6 内无重复数字数组');if(value.exceptions&&Object.entries(value.exceptions).some(([date,work])=>!isValidDate(date)||typeof work!=='boolean'))throw new Error('exceptions 必须为 ISO 日期到 true/false 的映射');this.plugin.settings.calendar=value;void this.plugin.saveSettings().then(()=>new Notice('工作日历已保存'));}catch(error){new Notice(err(error));}},true);
    c.append(node('h3','','容量配置示例'),node('p','','在 People 下的人员属性中设置 capacity.hoursPerDay 与 leave / meetings / support / buffer 周期扣减。未设置基础容量始终显示未知。每项扣减使用 periodStart、periodEnd、hours；不会自动采用 40 小时假设。'));
    const sample=node('pre','','capacity:\n  hoursPerDay: 8\n  meetings:\n    - periodStart: 2026-10-05\n      periodEnd: 2026-10-11\n      hours: 6');c.append(sample);
  }
}
