import { calculateCapacity, calculateLoad, compareBaseline, detectExceptions, isClosed, taskTouchesPeriod, type WorkbenchData, type WorkbenchSettings, type Period, type Task } from './domain';

export type TabId = 'home' | 'projects' | 'people' | 'coordination' | 'weekly';
export interface UIState { data: WorkbenchData; settings: WorkbenchSettings; period: Period; today: string; tab: TabId; search: string; project: string; warnings: string[]; baselineId?: string; }
export interface UIActions { tab:(id:TabId)=>void; search:(value:string)=>void; project:(value:string)=>void; period:(period:Period)=>void; task:(task:Task)=>void; open:(path?:string)=>void; create:()=>void; createRecord:(kind:'project'|'person'|'module'|'decision')=>void; import:()=>void; progress:()=>void; summary:()=>void; baseline:()=>void; chooseBaseline:(id:string)=>void; demo:()=>void; refresh:()=>void; settings:()=>void; }
export const STATUS_LABEL:Record<string,string> = {planned:'待开始','in-progress':'进行中',blocked:'受阻','dev-complete':'开发完成','test-passed':'测试通过',released:'已发布',accepted:'已验收',cancelled:'已取消'};
const tabLabels:Record<TabId,string>={home:'工作台',projects:'项目',people:'人员',coordination:'协调',weekly:'周计划'};
const glyph:Record<TabId,string>={home:'◫',projects:'▤',people:'♧',coordination:'⇄',weekly:'▦'};
function el<K extends keyof HTMLElementTagNameMap>(tag:K,cls='',text?:string):HTMLElementTagNameMap[K]{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function button(text:string,fn:()=>void,cls='elw-button'){const b=el('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;}
function badge(text:string,cls=''){return el('span',`elw-badge ${cls}`,text);}
function paragraph(parent:HTMLElement,text:string,cls='elw-muted'){parent.append(el('p',cls,text));}
function heading(parent:HTMLElement,title:string){const row=el('div','elw-section-title');row.append(el('h2','',title));parent.append(row);return row;}
function disclosure(parent:HTMLElement,label:string,text:string,cls='elw-disclosure'){const details=el('details',cls);details.append(el('summary','',label),el('p','',text));parent.append(details);return details;}
function empty(parent:HTMLElement,title:string,detail=''){const box=el('div','elw-empty');box.append(el('h3','',title));if(detail)box.append(el('p','',detail));parent.append(box);return box;}
function fmt(n:number|null|undefined){return n==null?'未知':`${Math.round(n*10)/10}`;}
const name=(data:WorkbenchData,id:string)=>data.people.find(p=>p.id===id)?.name||id||'未分配';
const projectName=(data:WorkbenchData,id:string)=>data.projects.find(p=>p.id===id)?.name||id||'未归属';
const moduleName=(data:WorkbenchData,id:string)=>data.modules.find(p=>p.id===id)?.name||id||'未归属';
function taskButton(task:Task,a:UIActions){const b=button(task.title,()=>a.task(task),'elw-text-button');b.title=`${task.id}\n来源：${task.source||'未说明'}\n更新：${task.lastUpdated||'未知'}`;return b;}
function taskTable(parent:HTMLElement,tasks:Task[],data:WorkbenchData,a:UIActions){
  if(!tasks.length){empty(parent,'暂无匹配任务','调整筛选或新建任务');return;}
  const wrap=el('div','elw-table-wrap'),table=el('table','elw-table'),head=el('thead'),tr=el('tr');
  ['任务','模块','执行人','状态','原承诺','当前预测','剩余工时'].forEach(t=>tr.append(el('th','',t)));head.append(tr);
  const body=el('tbody');for(const task of tasks){const row=el('tr'),title=el('td'),status=el('td');title.append(taskButton(task,a));status.append(badge(STATUS_LABEL[task.status]||task.status,`is-${task.status}`));row.append(title,el('td','',moduleName(data,task.module)),el('td','',name(data,task.executor)),status,el('td','elw-nowrap',task.originalDue||'未设定'),el('td','elw-nowrap',task.forecastDue||'未评估'),el('td','elw-number',`${fmt(task.remainingHours)}h`));body.append(row);}
  table.append(head,body);wrap.append(table);parent.append(wrap);
}
function metric(parent:HTMLElement,label:string,value:string,tone=''){const card=el('div',`elw-metric ${tone}`);card.append(el('span','elw-metric-label',label),el('strong','',value));parent.append(card);}
function nodeMilestones(milestones:NonNullable<WorkbenchData['projects'][number]['milestones']>){const list=el('div','elw-project-milestones');for(const m of milestones){const line=el('div','elw-milestone-row');line.append(el('span','elw-date',m.date),el('span','',m.title),badge(m.status==='completed'?'已完成':'计划',m.status==='completed'?'is-test-passed':''));list.append(line);}return list;}
function pageHelp(s:UIState){const closure=`闭环标准：${STATUS_LABEL[s.settings.closureStatus]}。`;return ({
  home:`${closure}预测日期以当前依赖和容量不变为前提。点击任务可查看来源、更新时间及事实 / 预测 / 判断。`,
  projects:`${closure}开发、测试、发布和验收分别记录。模块负责人是稳定责任归属，任务执行人是当前分工。`,
  people:'所有人员负荷跨项目汇总，不受项目筛选影响。可用容量按实际日历减去请假、会议、支持和缓冲。余量仅在分配、依赖和扣减不变时成立；未知容量或未排期任务不能视为空闲。负荷不用于个人绩效排名。',
  coordination:'任务详情保留来源和更新时间。决策仅记录已确认内容，风险判断不当作已发生事实。',
  weekly:`${closure}冻结基线不随任务更新而改变。新增范围不纳入原承诺分母；预测延后与冻结时的日期比较。`
})[s.tab];}
const fieldLabels:Record<string,string>={status:'状态',forecastDue:'预测日期',executor:'执行人',remainingHours:'剩余工时',allocations:'周期投入',nextAction:'下一步',originalStart:'原开始',originalDue:'原承诺',project:'项目',module:'模块',dependencies:'依赖'};
function changeValue(field:string,value:unknown){if(field==='status'&&typeof value==='string')return STATUS_LABEL[value]||value;if(value==null)return '空';return typeof value==='object'?JSON.stringify(value):String(value);}

export function renderWorkbench(container:HTMLElement,s:UIState,a:UIActions):void{
  container.replaceChildren();container.className='elw';
  const data=s.data,allPeople=[...data.people];for(const t of data.tasks)if(t.executor&&!allPeople.some(p=>p.id===t.executor))allPeople.push({id:t.executor,name:t.executor,source:'任务执行人（尚无人员记录）'});
  const lower=s.search.toLowerCase();
  const filtered=data.tasks.filter(t=>(!s.project||t.project===s.project)&&(!lower||[t.id,t.title,t.project,t.module,t.executor,t.nextAction,t.risk,t.blocker].join(' ').toLowerCase().includes(lower)));
  const open=filtered.filter(t=>!isClosed(t,s.settings.closureStatus)&&t.status!=='cancelled'),visibleTaskIds=new Set(filtered.map(t=>t.id));
  const exceptions=detectExceptions(data.tasks,{today:s.today,...s.settings,people:data.people,period:s.period}).filter(e=>e.taskId?visibleTaskIds.has(e.taskId):true);
  const rail=el('aside','elw-rail'),brand=el('div','elw-brand');brand.append(el('span','elw-logo','E'),el('div','','研发负责人工作台'));rail.append(brand);
  const nav=el('nav','elw-nav');nav.setAttribute('aria-label','工作台视图');nav.setAttribute('role','tablist');
  (Object.keys(tabLabels) as TabId[]).forEach(id=>{const b=button('',()=>a.tab(id),`elw-nav-item ${s.tab===id?'is-active':''}`),icon=el('span','elw-nav-icon',glyph[id]);icon.setAttribute('aria-hidden','true');b.append(icon,el('span','',tabLabels[id]));b.id=`elw-tab-${id}`;b.setAttribute('aria-label',tabLabels[id]);b.setAttribute('role','tab');b.setAttribute('aria-selected',String(s.tab===id));b.setAttribute('aria-controls','elw-panel');b.tabIndex=s.tab===id?0:-1;b.addEventListener('keydown',e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const ids=Object.keys(tabLabels) as TabId[];let i=ids.indexOf(id);i=e.key==='Home'?0:e.key==='End'?4:(i+(['ArrowDown','ArrowRight'].includes(e.key)?1:4))%5;a.tab(ids[i]);container.querySelector<HTMLButtonElement>(`#elw-tab-${ids[i]}`)?.focus();}});nav.append(b);});rail.append(nav);
  const railBottom=el('div','elw-rail-bottom');railBottom.append(button('设置',a.settings,'elw-text-button'));rail.append(railBottom);container.append(rail);
  const main=el('main','elw-main');main.id='elw-panel';main.setAttribute('role','tabpanel');main.setAttribute('aria-labelledby',`elw-tab-${s.tab}`);main.tabIndex=0;container.append(main);
  const top=el('header','elw-topbar'),title=el('div','elw-page-title');title.append(el('h1','',tabLabels[s.tab]));disclosure(title,'口径',pageHelp(s),'elw-help');top.append(title);
  const toolbar=el('div','elw-toolbar');toolbar.append(button('↻',a.refresh,'elw-icon-button'),button('导入',a.import,'elw-button elw-quiet'),button('整理进展',a.progress,'elw-button elw-quiet'),button('+ 任务',a.create,'elw-button elw-primary'));toolbar.children[0].setAttribute('aria-label','刷新工作台');toolbar.children[2].setAttribute('aria-label','整理本次进展');toolbar.children[3].setAttribute('aria-label','新建任务');top.append(toolbar);main.append(top);
  const filters=el('div','elw-filters'),periodGroup=el('div','elw-period');periodGroup.append(el('span','elw-filter-label','周期'));
  for(const [key,label] of [['start','开始日期'],['end','结束日期']] as const){const input=el('input');input.type='date';input.value=s.period[key];input.setAttribute('aria-label',label);input.addEventListener('change',()=>a.period({...s.period,[key]:input.value}));periodGroup.append(input);if(key==='start')periodGroup.append(el('span','','→'));}filters.append(periodGroup);
  const select=el('select','elw-select');select.setAttribute('aria-label','项目筛选');const all=el('option','','全部项目');all.value='';select.append(all);data.projects.forEach(p=>{const opt=el('option','',p.name);opt.value=p.id;select.append(opt);});select.value=s.project;select.addEventListener('change',()=>a.project(select.value));filters.append(select);
  const search=el('input','elw-search');search.type='search';search.placeholder='搜索任务';search.value=s.search;search.setAttribute('aria-label','搜索任务');search.addEventListener('change',()=>a.search(search.value));search.addEventListener('keydown',e=>{if(e.key==='Enter')a.search(search.value)});filters.append(search);main.append(filters);
  if(s.warnings.length){const details=el('details','elw-warning');details.append(el('summary','',`${s.warnings.length} 条数据错误，部分记录未读取`));s.warnings.forEach(w=>details.append(el('p','',w)));main.append(details);}
  if(!data.tasks.length){const box=empty(main,'暂无任务'),actions=el('div','elw-empty-actions');actions.append(button('创建虚构示例',a.demo),button('导入 CSV / JSON',a.import),button('新建任务',a.create,'elw-button elw-primary'));box.append(actions);return;}
  if(s.tab==='home'){
    const metrics=el('div','elw-metrics');metric(metrics,'优先异常',String(exceptions.filter(e=>e.severity==='high').length),'is-attention');metric(metrics,'未闭环',String(open.length));metric(metrics,'本期预计交付',String(open.filter(t=>t.forecastDue>=s.period.start&&t.forecastDue<=s.period.end).length));metric(metrics,'容量未知',String(allPeople.filter(p=>calculateCapacity(p,s.period,s.settings.calendar).status==='unknown').length));main.append(metrics);
    const columns=el('div','elw-columns'),primary=el('section','elw-panel');heading(primary,'待处理').append(badge(String(exceptions.length)));if(!exceptions.length)empty(primary,'暂无异常');
    exceptions.slice(0,8).forEach(ex=>{const card=el('article',`elw-exception ${ex.severity==='high'?'is-high':''}`),line=el('div','elw-card-title'),task=data.tasks.find(t=>t.id===ex.taskId);line.append(badge(ex.severity==='high'?'优先':'待确认',ex.severity==='high'?'is-alert':''));if(task)line.append(taskButton(task,a));else line.append(el('h3','',ex.title));card.append(line,el('p','',ex.reason));if(task){const next=el('div','elw-next');next.append(el('span','','下一步'),el('strong','',task.nextAction||'待补充'));card.append(next);}else disclosure(card,'来源',ex.source);primary.append(card);});columns.append(primary);
    const side=el('section','elw-panel');heading(side,'本期预计交付');const due=open.filter(t=>t.forecastDue>=s.period.start&&t.forecastDue<=s.period.end).sort((a,b)=>a.forecastDue.localeCompare(b.forecastDue));if(!due.length)empty(side,'暂无预计交付');due.slice(0,6).forEach(t=>{const card=el('article','elw-milestone');card.append(el('div','elw-date',t.forecastDue.slice(5)),taskButton(t,a),el('p','elw-muted',`${projectName(data,t.project)} · ${name(data,t.executor)}`),badge(STATUS_LABEL[t.status],`is-${t.status}`));side.append(card);});columns.append(side);main.append(columns);
  }else if(s.tab==='projects'){
    const cards=el('div','elw-project-grid');data.projects.filter(p=>!s.project||p.id===s.project).forEach(p=>{const tasks=filtered.filter(t=>t.project===p.id),closed=tasks.filter(t=>isClosed(t,s.settings.closureStatus)&&t.status!=='cancelled').length,card=el('article','elw-panel'),row=heading(card,p.name);if(p.path)row.append(button('打开 ↗',()=>a.open(p.path),'elw-text-button'));if(p.description)disclosure(card,'范围',p.description);const stats=el('div','elw-project-stat');stats.append(el('strong','',`${closed} / ${tasks.length}`),el('span','elw-muted','已闭环'));card.append(stats);const progress=el('progress');progress.max=tasks.length||1;progress.value=closed;progress.setAttribute('aria-label',`${p.name} 已闭环 ${closed} / ${tasks.length}`);card.append(progress);paragraph(card,`${name(data,p.owner||'')} · ${p.targetDate||'未设目标日期'}`);if(p.milestones?.length)card.append(nodeMilestones(p.milestones));for(const m of data.modules.filter(m=>m.project===p.id)){const row=el('div','elw-module-row');row.append(el('span','',m.name),el('span','elw-muted',name(data,m.owner||'')));row.title='模块负责人';card.append(row);}cards.append(card);});main.append(cards);const row=heading(main,'任务');row.append(button('+ 项目',()=>a.createRecord('project'),'elw-text-button'),button('+ 模块',()=>a.createRecord('module'),'elw-text-button'));taskTable(main,filtered,data,a);
  }else if(s.tab==='people'){
    const row=heading(main,'本期容量');row.append(badge('跨项目'),button('+ 人员',()=>a.createRecord('person'),'elw-text-button'));const cards=el('div','elw-people-grid');
    allPeople.forEach(p=>{const cap=calculateCapacity(p,s.period,s.settings.calendar),load=calculateLoad(data.tasks,p.id,s.period,p.calendar||s.settings.calendar,s.settings.closureStatus),card=el('article','elw-panel elw-person'),title=el('div','elw-person-head');title.append(el('div','elw-avatar',p.name.slice(-1)),el('h3','',p.name));if(cap.availableHours===null)title.append(badge('容量未知'));else if(load.allocatedHours>cap.availableHours)title.append(badge('超出容量','is-alert'));card.append(title);const values=el('div','elw-capacity-value');values.append(el('strong','',`${fmt(load.allocatedHours)}h`),el('span','elw-muted',` / ${fmt(cap.availableHours)}${cap.availableHours===null?'':'h'}`),el('span','elw-small','已排 / 可用'));card.append(values);
      if(cap.availableHours!==null){const bar=el('div','elw-load-bar');bar.setAttribute('role','img');bar.setAttribute('aria-label',`已分配 ${load.allocatedHours} 小时，可用 ${cap.availableHours} 小时`);const fill=el('div',load.allocatedHours>cap.availableHours?'is-over':'');fill.style.width=`${Math.min(100,cap.availableHours?load.allocatedHours/cap.availableHours*100:load.allocatedHours?100:0)}%`;bar.append(fill);card.append(bar);disclosure(card,'容量明细',`${cap.workingDays} 个工作日 · 基础 ${fmt(cap.grossHours)}h\n请假 ${fmt(cap.leaveHours)}h · 会议 ${fmt(cap.meetingsHours)}h · 支持 ${fmt(cap.supportHours)}h · 缓冲 ${fmt(cap.bufferHours)}h`);}
      const own=data.modules.filter(m=>m.owner===p.id);if(own.length)paragraph(card,`负责 · ${own.map(m=>m.name).join('、')}`);
      const slack=cap.availableHours==null?null:cap.availableHours-load.allocatedHours;
      if(load.unallocatedTaskIds.length)paragraph(card,`${load.unallocatedTaskIds.length} 项未排期，余量待确认`,'elw-capacity-status elw-danger');
      else if(slack===null)paragraph(card,'可接新任务时间未知','elw-capacity-status');
      else paragraph(card,slack>0?`预计余量 ${fmt(slack)}h`:'本期无余量','elw-capacity-status');
      cap.warnings.forEach(w=>paragraph(card,w,'elw-small elw-danger'));if(p.path)card.append(button(cap.status==='unknown'?'补充容量 ↗':'编辑容量 ↗',()=>a.open(p.path),'elw-text-button'));cards.append(card);
    });main.append(cards);
  }else if(s.tab==='coordination'){
    heading(main,'待协调');const tasks=filtered.filter(t=>!isClosed(t,s.settings.closureStatus)&&t.status!=='cancelled'&&(t.status==='blocked'||t.blocker||t.dependencies.length||t.coordinationDue));if(!tasks.length)empty(main,'暂无协调事项');for(const t of tasks){const card=el('article','elw-panel elw-coordination'),line=el('div','elw-card-title');line.append(taskButton(t,a),badge(t.status==='blocked'?'受阻':'依赖跟进',t.status==='blocked'?'is-alert':''));card.append(line,el('p','',t.blocker||`依赖 ${t.dependencies.join('、')||'未填写'}`));const grid=el('div','elw-coord-grid');for(const [label,value]of [['对接人',name(data,t.contact||t.executor)],['下一步',t.nextAction||'待补充'],['到期日',t.coordinationDue||'未设置']]){const cell=el('div');cell.append(el('span','elw-field-label',label),el('strong','',value));grid.append(cell);}card.append(grid);main.append(card);}
    heading(main,'决策').append(button('+ 决策',()=>a.createRecord('decision'),'elw-text-button'));data.decisions.filter(d=>!s.project||d.project===s.project).sort((a,b)=>b.date.localeCompare(a.date)).forEach(d=>{const card=el('article','elw-decision');card.append(el('span','elw-date',`${d.date} · ${name(data,d.owner)}`),el('h3','',d.title),el('p','',d.decision));const details=disclosure(card,'来源',d.source);if(d.path)details.append(button('打开决策 ↗',()=>a.open(d.path),'elw-text-button'));main.append(card);});
  }else{
    const row=heading(main,'本期基线');row.append(button('冻结基线',a.baseline,'elw-button'),button('周会摘要',a.summary,'elw-button elw-primary'));
    const baseline=data.baselines.find(b=>b.id===s.baselineId)||data.baselines.filter(b=>b.period?.start===s.period.start&&b.period?.end===s.period.end).slice(-1)[0];
    if(data.baselines.length){const select=el('select','elw-select');select.setAttribute('aria-label','选择基线');const opt=el('option','','选择基线');opt.value='';select.append(opt);data.baselines.forEach(b=>{const o=el('option','',`${b.name} · ${b.createdAt.slice(0,10)}`);o.value=b.id;select.append(o);});select.value=baseline?.id||'';select.addEventListener('change',()=>a.chooseBaseline(select.value));main.append(select);}
    if(baseline){const comparison=compareBaseline(baseline,data.tasks),promised=baseline.tasks.filter(t=>t.status!=='cancelled'),closed=promised.filter(t=>{const current=data.tasks.find(c=>c.id===t.id);return current&&current.status!=='cancelled'&&isClosed(current,s.settings.closureStatus);}),metrics=el('div','elw-metrics');metric(metrics,'原承诺',String(promised.length));metric(metrics,'承诺闭环',`${closed.length} / ${promised.length}`);metric(metrics,'新增范围',String(comparison.added));metric(metrics,'预测延后',String(comparison.slipped),'is-attention');main.append(metrics);
      const panel=el('section','elw-panel');heading(panel,'变化');if(!comparison.changes.length)paragraph(panel,'与基线一致');for(const change of comparison.changes){const task=data.tasks.find(t=>t.id===change.taskId)||baseline.tasks.find(t=>t.id===change.taskId),line=el('div','elw-baseline-change');line.append(badge(change.type==='added'?'新增':change.type==='removed'?'移出 / 缺失':'变更'),el('strong','',task?.title||change.taskId));if(change.type==='changed')disclosure(line,'查看变化',change.fields.map(f=>`${fieldLabels[f.field]||f.field}：${changeValue(f.field,f.baseline)} → ${changeValue(f.field,f.current)}`).join('\n'));panel.append(line);}const info=disclosure(panel,'基线记录',`冻结时间：${baseline.createdAt}`);if(baseline.path)info.append(button('打开基线 ↗',()=>a.open(baseline.path),'elw-text-button'));main.append(panel);
    }else empty(main,'尚未冻结基线');
    heading(main,'本期任务');taskTable(main,filtered.filter(t=>taskTouchesPeriod(t,s.period)),data,a);
  }
}
