import { calculateCapacity, calculateLoad, compareBaseline, detectExceptions, isClosed, taskTouchesPeriod, type WorkbenchData, type WorkbenchSettings, type Period, type Task } from './domain';

export type TabId = 'home' | 'projects' | 'people' | 'coordination' | 'weekly';
export interface UIState { data: WorkbenchData; settings: WorkbenchSettings; period: Period; today: string; tab: TabId; search: string; project: string; warnings: string[]; baselineId?: string; }
export interface UIActions { tab:(id:TabId)=>void; search:(value:string)=>void; project:(value:string)=>void; period:(period:Period)=>void; task:(task:Task)=>void; open:(path?:string)=>void; create:()=>void; createRecord:(kind:'project'|'person'|'module'|'decision')=>void; import:()=>void; progress:()=>void; summary:()=>void; baseline:()=>void; chooseBaseline:(id:string)=>void; demo:()=>void; refresh:()=>void; settings:()=>void; }
export const STATUS_LABEL:Record<string,string> = {planned:'待开始','in-progress':'进行中',blocked:'受阻','dev-complete':'开发完成','test-passed':'测试通过',released:'已发布',accepted:'已验收',cancelled:'已取消'};
const tabLabels:Record<TabId,string>={home:'工作台',projects:'项目',people:'人员',coordination:'协调',weekly:'周计划'};
const glyph:Record<TabId,string>={home:'◫',projects:'▤',people:'♧',coordination:'⇄',weekly:'▦'};
function el<K extends keyof HTMLElementTagNameMap>(tag:K, cls='',text?:string):HTMLElementTagNameMap[K] {const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function button(text:string,fn:()=>void,cls='elw-button'){const b=el('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;}
function badge(text:string,cls=''){return el('span',`elw-badge ${cls}`,text);}
function paragraph(parent:HTMLElement,text:string,cls='elw-muted'){parent.append(el('p',cls,text));}
function heading(parent:HTMLElement,title:string,sub?:string){const row=el('div','elw-section-title');row.append(el('h2','',title));parent.append(row);if(sub)paragraph(parent,sub);return row;}
function empty(parent:HTMLElement,title:string,detail:string){const box=el('div','elw-empty');box.append(el('span','elw-empty-mark','◎'),el('h3','',title),el('p','',detail));parent.append(box);return box;}
function fmt(n:number|null|undefined){return n==null?'未知':`${Math.round(n*10)/10}`;}
const name=(data:WorkbenchData,id:string)=>data.people.find(p=>p.id===id)?.name||id||'未分配';
const projectName=(data:WorkbenchData,id:string)=>data.projects.find(p=>p.id===id)?.name||id||'未归属';
const moduleName=(data:WorkbenchData,id:string)=>data.modules.find(p=>p.id===id)?.name||id||'未归属';
function taskRow(task:Task,data:WorkbenchData,a:UIActions){const tr=el('tr');const title=el('td');const b=button(task.title,()=>a.task(task),'elw-text-button');title.append(b,el('small','elw-id',task.id));tr.append(title,el('td','',moduleName(data,task.module)),el('td','',name(data,task.executor)));const status=el('td');status.append(badge(STATUS_LABEL[task.status]||task.status,`is-${task.status}`));tr.append(status,el('td','elw-nowrap',task.originalDue||'未设定'),el('td','elw-nowrap',task.forecastDue||'未评估'),el('td','elw-number',`${fmt(task.remainingHours)}h`));return tr;}
function taskTable(parent:HTMLElement,tasks:Task[],data:WorkbenchData,a:UIActions){if(!tasks.length){empty(parent,'暂无匹配任务','尝试调整项目、周期或搜索条件，或添加共享任务记录。');return;}const wrap=el('div','elw-table-wrap');const table=el('table','elw-table');const head=el('thead');const tr=el('tr');['任务 / 来源记录','模块','执行人','状态','原承诺','当前预测','剩余工作'].forEach(t=>tr.append(el('th','',t)));head.append(tr);const body=el('tbody');tasks.forEach(t=>body.append(taskRow(t,data,a)));table.append(head,body);wrap.append(table);parent.append(wrap);}
function metric(parent:HTMLElement,label:string,value:string,detail:string,tone=''){const card=el('div',`elw-metric ${tone}`);card.append(el('span','elw-eyebrow',label),el('strong','',value),el('span','elw-muted',detail));parent.append(card);}
function linkSource(parent:HTMLElement,task:Task,a:UIActions){const line=el('div','elw-source');line.append(el('span','',`来源 ${task.source||'未说明'} · 更新 ${task.lastUpdated?.slice(0,10)||'未知'}`));if(task.path)line.append(button('查看记录 ↗',()=>a.open(task.path),'elw-text-button'));parent.append(line);}

function nodeMilestones(milestones:NonNullable<WorkbenchData['projects'][number]['milestones']>){const list=el('div','elw-project-milestones');for(const m of milestones){const line=el('div','elw-milestone-row');line.append(el('span','elw-date',m.date),el('span','',m.title),badge(m.status==='completed'?'已确认完成':'计划里程碑',m.status==='completed'?'is-test-passed':''));list.append(line);}return list;}

export function renderWorkbench(container:HTMLElement,s:UIState,a:UIActions):void {
  container.replaceChildren();container.className='elw';
  const data=s.data;const allPeople=[...data.people];for(const t of data.tasks){if(t.executor&&!allPeople.some(p=>p.id===t.executor))allPeople.push({id:t.executor,name:t.executor,source:'任务执行人（尚无人员记录）'});}const lower=s.search.toLowerCase();
  const filtered=data.tasks.filter(t=>(!s.project||t.project===s.project)&&(!lower||[t.id,t.title,t.project,t.module,t.executor,t.nextAction,t.risk,t.blocker].join(' ').toLowerCase().includes(lower)));
  const open=filtered.filter(t=>!isClosed(t,s.settings.closureStatus)&&t.status!=='cancelled');
  const visibleTaskIds=new Set(filtered.map(t=>t.id));
  const exceptions=detectExceptions(data.tasks,{today:s.today,...s.settings,people:data.people,period:s.period}).filter(e=>e.taskId?visibleTaskIds.has(e.taskId):true);
  const rail=el('aside','elw-rail');const brand=el('div','elw-brand');brand.append(el('span','elw-logo','E'),el('div','','研发负责人工作台'));rail.append(brand,el('div','elw-rail-caption','ENGINEERING LEAD'));
  const nav=el('nav','elw-nav');nav.setAttribute('aria-label','工作台视图');nav.setAttribute('role','tablist');
  (Object.keys(tabLabels) as TabId[]).forEach(id=>{const b=button('',()=>a.tab(id),`elw-nav-item ${s.tab===id?'is-active':''}`);b.append(el('span','elw-nav-icon',glyph[id]),el('span','',tabLabels[id]));b.id=`elw-tab-${id}`;b.setAttribute('aria-label',tabLabels[id]);b.setAttribute('role','tab');b.setAttribute('aria-selected',String(s.tab===id));b.setAttribute('aria-controls','elw-panel');b.tabIndex=s.tab===id?0:-1;b.addEventListener('keydown',e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const ids=Object.keys(tabLabels) as TabId[];let i=ids.indexOf(id);i=e.key==='Home'?0:e.key==='End'?4:(i+(['ArrowDown','ArrowRight'].includes(e.key)?1:4))%5;a.tab(ids[i]);container.querySelector<HTMLButtonElement>(`#elw-tab-${ids[i]}`)?.focus();}});nav.append(b);});rail.append(nav);
  const railBottom=el('div','elw-rail-bottom');railBottom.append(badge('● 本地优先','is-local'),el('p','','共享记录，多维视图\n数据始终留在你的 Vault'),button('偏好设置',a.settings,'elw-text-button'));rail.append(railBottom);container.append(rail);
  const main=el('main','elw-main');main.id='elw-panel';main.setAttribute('role','tabpanel');main.setAttribute('aria-labelledby',`elw-tab-${s.tab}`);main.tabIndex=0;container.append(main);
  const top=el('header','elw-topbar');const crumb=el('div','elw-breadcrumb');crumb.append(el('span','','负责人视角'),el('span','',' / '),el('strong','',tabLabels[s.tab]));top.append(crumb);const toolbar=el('div','elw-toolbar');toolbar.append(button('↻',a.refresh,'elw-icon-button'),button('导入',a.import,'elw-button elw-quiet'),button('整理本次进展',a.progress,'elw-button elw-quiet'),button('+ 新建任务',a.create,'elw-button elw-primary'));toolbar.children[0].setAttribute('aria-label','刷新工作台');top.append(toolbar);main.append(top);
  const intro=el('div','elw-intro');const introText=el('div');introText.append(el('div','elw-eyebrow','CLARITY BEFORE VELOCITY'),el('h1','',({home:'把注意力，留给需要推动的事',projects:'从范围到交付，看清项目全貌',people:'让承诺，落在真实容量里',coordination:'每一个卡点，都有下一步',weekly:'保留承诺，也看见计划的变化'})[s.tab]),el('p','elw-muted',({home:'异常、里程碑与下一步行动，来自同一份共享任务记录。',projects:'稳定负责人、当前执行人、依赖与决策，保持可追溯。',people:'跨项目统计本周期投入。负荷只服务于排期，不用于个人绩效排名。',coordination:'跟进对象、到期时间与决策依据，放在一起。',weekly:'基线一经确认即冻结；新增范围与预测变化单独呈现。'})[s.tab]));intro.append(introText);main.append(intro);
  const filters=el('div','elw-filters');const periodGroup=el('div','elw-period');periodGroup.append(el('span','elw-filter-label','观察周期'));for(const [key,label] of [['start','开始日期'],['end','结束日期']] as const){const input=el('input');input.type='date';input.value=s.period[key];input.setAttribute('aria-label',label);input.addEventListener('change',()=>a.period({...s.period,[key]:input.value}));periodGroup.append(input);if(key==='start')periodGroup.append(el('span','','→'));}filters.append(periodGroup);
  const select=el('select','elw-select');select.setAttribute('aria-label','项目筛选');const all=el('option','','全部项目');all.value='';select.append(all);data.projects.forEach(p=>{const opt=el('option','',p.name);opt.value=p.id;select.append(opt);});select.value=s.project;select.addEventListener('change',()=>a.project(select.value));filters.append(select);
  const search=el('input','elw-search');search.type='search';search.placeholder='搜索任务、模块、下一步…';search.value=s.search;search.setAttribute('aria-label','搜索任务');search.addEventListener('change',()=>a.search(search.value));search.addEventListener('keydown',e=>{if(e.key==='Enter')a.search(search.value)});filters.append(search);main.append(filters);
  if(s.warnings.length){const details=el('details','elw-warning');details.append(el('summary','',`${s.warnings.length} 条数据校验提醒，部分记录未读取`));s.warnings.forEach(w=>details.append(el('p','',w)));main.append(details);}
  if(!data.tasks.length){const box=empty(main,'为这周建立一张清晰的工作地图','从 Markdown 任务、TAPD / WBS 导出文件开始，也可以体验完全虚构的示例。');const actions=el('div','elw-empty-actions');actions.append(button('创建虚构示例',a.demo,'elw-button elw-primary'),button('导入 CSV / JSON',a.import),button('新建第一条任务',a.create));box.append(actions);return;}
  if(s.tab==='home'){
    const metrics=el('div','elw-metrics');metric(metrics,'需要推动',String(exceptions.filter(e=>e.severity==='high').length),'高优先级异常','is-attention');metric(metrics,'进行中的任务',String(open.length),`已闭环 ${filtered.filter(t=>isClosed(t,s.settings.closureStatus)&&t.status!=='cancelled').length} · 以${STATUS_LABEL[s.settings.closureStatus]}为准`);metric(metrics,'本周期交付',String(open.filter(t=>t.forecastDue>=s.period.start&&t.forecastDue<=s.period.end).length),'当前预测，包含前置条件');metric(metrics,'待确认容量',String(allPeople.filter(p=>calculateCapacity(p,s.period,s.settings.calendar).status==='unknown').length),'未知不代表空闲');main.append(metrics);
    const columns=el('div','elw-columns');const primary=el('section','elw-panel');const title=heading(primary,'优先关注','先解决影响承诺的异常，再增加新的承诺。');title.append(badge(String(exceptions.length)));if(!exceptions.length)empty(primary,'当前没有触发异常规则','这不等于没有风险；可核对来源与更新时间。');exceptions.slice(0,8).forEach(ex=>{const card=el('article',`elw-exception ${ex.severity==='high'?'is-high':''}`);const line=el('div','elw-card-title');line.append(badge(ex.severity==='high'?'优先推动':'需要确认',ex.severity==='high'?'is-alert':''),el('h3','',ex.title));card.append(line,el('p','',ex.reason));const task=data.tasks.find(t=>t.id===ex.taskId);if(task){const next=el('div','elw-next');next.append(el('span','','下一步'),el('strong','',task.nextAction||'尚未填写，请补充可执行动作'));card.append(next);card.append(button('查看并更新 →',()=>a.task(task),'elw-text-button'));linkSource(card,task,a);}else paragraph(card,`来源 ${ex.source}`,'elw-source');primary.append(card);});columns.append(primary);
    const side=el('section','elw-panel');heading(side,'临近交付','预测日期并非保证；请核实依赖与容量。');const due=open.filter(t=>t.forecastDue>=s.period.start&&t.forecastDue<=s.period.end).sort((a,b)=>a.forecastDue.localeCompare(b.forecastDue));if(!due.length)empty(side,'本周期暂无预测交付','为任务填写预测日期后会显示在这里。');due.slice(0,6).forEach(t=>{const card=el('article','elw-milestone');card.append(el('div','elw-date',t.forecastDue.slice(5)),button(t.title,()=>a.task(t),'elw-text-button'),el('p','elw-muted',`${projectName(data,t.project)} · ${name(data,t.executor)}`),badge(STATUS_LABEL[t.status],`is-${t.status}`));side.append(card);});const note=el('div','elw-note');note.append(el('strong','','事实 ≠ 预测 ≠ 判断'),el('p','','原承诺不会被预测覆盖；事实和判断各自保留来源及记录时间。'));side.append(note);columns.append(side);main.append(columns);
  } else if(s.tab==='projects'){
    const cards=el('div','elw-project-grid');data.projects.filter(p=>!s.project||p.id===s.project).forEach(p=>{const tasks=filtered.filter(t=>t.project===p.id);const closed=tasks.filter(t=>isClosed(t,s.settings.closureStatus)&&t.status!=='cancelled').length;const card=el('article','elw-panel');const row=heading(card,p.name);if(p.path)row.append(button('打开项目 ↗',()=>a.open(p.path),'elw-text-button'));paragraph(card,p.description||'在项目记录中填写范围与目标。');const stats=el('div','elw-project-stat');stats.append(el('strong','',`${closed} / ${tasks.length}`),el('span','elw-muted',`任务达到${STATUS_LABEL[s.settings.closureStatus]}`));card.append(stats);const progress=el('progress');progress.max=tasks.length||1;progress.value=closed;progress.setAttribute('aria-label',`${p.name} 已闭环 ${closed} / ${tasks.length}`);card.append(progress);paragraph(card,`负责人 ${name(data,p.owner||'')} · 目标日期 ${p.targetDate||'未设置'}`);if(p.milestones?.length){const ms=nodeMilestones(p.milestones);card.append(ms);}const mods=data.modules.filter(m=>m.project===p.id);mods.forEach(m=>{const row=el('div','elw-module-row');row.append(el('span','',m.name),el('span','elw-muted',`Owner · ${name(data,m.owner||'')}`));card.append(row);});cards.append(card);});main.append(cards);const row=heading(main,'共享任务','开发完成、测试通过、发布与验收分别记录。点击任务查看依赖、风险和证据。');row.append(button('+ 项目',()=>a.createRecord('project'),'elw-text-button'),button('+ 模块',()=>a.createRecord('module'),'elw-text-button'));taskTable(main,filtered,data,a);
  }else if(s.tab==='people'){
    const row=heading(main,'本周期容量与投入','投入按观察周期计算，跨项目汇总；不把全部积压任务当作本周工作。');row.append(button('+ 人员',()=>a.createRecord('person'),'elw-text-button'));const cards=el('div','elw-people-grid');allPeople.forEach(p=>{const cap=calculateCapacity(p,s.period,s.settings.calendar);const load=calculateLoad(data.tasks,p.id,s.period,p.calendar||s.settings.calendar,s.settings.closureStatus);const card=el('article','elw-panel elw-person');const title=el('div','elw-person-head');title.append(el('div','elw-avatar',p.name.slice(-1)),el('h3','',p.name),badge(cap.availableHours===null?'容量未知':load.allocatedHours>cap.availableHours?'投入超出容量':'可核对',cap.availableHours!==null&&load.allocatedHours>cap.availableHours?'is-alert':''));card.append(title);const values=el('div','elw-capacity-value');values.append(el('strong','',`${fmt(load.allocatedHours)}h`),el('span','elw-muted',` / ${fmt(cap.availableHours)}${cap.availableHours===null?'':'h'} 可用`));card.append(values);if(cap.availableHours!==null){const bar=el('div','elw-load-bar');bar.setAttribute('role','img');bar.setAttribute('aria-label',`已分配 ${load.allocatedHours} 小时，可用 ${cap.availableHours} 小时`);const fill=el('div',load.allocatedHours>cap.availableHours?'is-over':'');fill.style.width=`${Math.min(100,cap.availableHours?load.allocatedHours/cap.availableHours*100:load.allocatedHours?100:0)}%`;bar.append(fill);card.append(bar);paragraph(card,`${cap.workingDays} 个工作日 · 基础 ${fmt(cap.grossHours)}h`);paragraph(card,`请假 ${fmt(cap.leaveHours)} · 会议 ${fmt(cap.meetingsHours)} · 支持 ${fmt(cap.supportHours)} · 缓冲 ${fmt(cap.bufferHours)}h`,'elw-small');}else paragraph(card,'未配置基础容量，无法判断空闲。请打开人员记录补充工作日历与 hoursPerDay。');const own=data.modules.filter(m=>m.owner===p.id);paragraph(card,`稳定负责 ${own.map(m=>m.name).join('、')||'未设置模块'}`,'elw-small');const taskSet=data.tasks.filter(t=>t.executor===p.id&&!isClosed(t,s.settings.closureStatus)&&t.status!=='cancelled');const latest=taskSet.map(t=>t.forecastDue).filter(Boolean).sort().pop();const slack=cap.availableHours==null?null:cap.availableHours-load.allocatedHours;paragraph(card,load.unallocatedTaskIds.length?'可接新任务时间：待确认，先补齐未分配任务的周期投入':slack===null?'可接新任务时间：未知':slack>0?`条件预测：本周期尚有 ${fmt(slack)}h；仅在当前分配、依赖与扣减不变时成立`:`条件预测：当前周期无剩余容量${latest?`；现有任务最晚预测 ${latest}`:''}，需重新确认`,'elw-conditional');if(load.unallocatedTaskIds.length)paragraph(card,`${load.unallocatedTaskIds.length} 个未闭环任务缺少周期投入，负荷可能低估`,'elw-small elw-danger');cap.warnings.forEach(w=>paragraph(card,w,'elw-small elw-danger'));if(p.path)card.append(button('编辑容量记录 ↗',()=>a.open(p.path),'elw-text-button'));cards.append(card);});main.append(cards);paragraph(main,'模块 Owner 是稳定责任归属，执行人是当前任务分配；两者可以不同。人员容量始终跨项目计算，不受顶部项目筛选影响。','elw-note');
  }else if(s.tab==='coordination'){
    heading(main,'协调清单','受阻任务和依赖都要有对接人、下一步与到期日。');const tasks=filtered.filter(t=>!isClosed(t,s.settings.closureStatus)&&t.status!=='cancelled'&&(t.status==='blocked'||t.blocker||t.dependencies.length||t.coordinationDue));if(!tasks.length)empty(main,'没有需要协调的任务','你可以在任务详情里补充阻塞说明、依赖、对接人和跟进到期日。');tasks.forEach(t=>{const card=el('article','elw-panel elw-coordination');const line=el('div','elw-card-title');line.append(button(t.title,()=>a.task(t),'elw-text-button'),badge(t.status==='blocked'?'受阻':'依赖跟进',t.status==='blocked'?'is-alert':''));card.append(line,el('p','',t.blocker||`依赖 ${t.dependencies.join('、')||'未填写'}`));const grid=el('div','elw-coord-grid');for(const [label,value]of [['对接人',name(data,t.contact||t.executor)],['下一步',t.nextAction||'待补充'],['到期日',t.coordinationDue||'未设置']]){const cell=el('div');cell.append(el('span','elw-eyebrow',label),el('strong','',value));grid.append(cell);}card.append(grid);linkSource(card,t,a);main.append(card);});const row=heading(main,'决策日志','保留决定、负责人、日期与来源；不把推测改写成已做决定。');row.append(button('+ 记录决策',()=>a.createRecord('decision'),'elw-text-button'));data.decisions.filter(d=>!s.project||d.project===s.project).sort((a,b)=>b.date.localeCompare(a.date)).forEach(d=>{const card=el('article','elw-decision');card.append(el('span','elw-date',d.date),el('h3','',d.title),el('p','',d.decision),el('span','elw-source',`${name(data,d.owner)} · 来源 ${d.source}`));if(d.path)card.append(button('打开决策 ↗',()=>a.open(d.path),'elw-text-button'));main.append(card);});
  }else{
    const row=heading(main,'本周承诺与变化','冻结的是选定周期的任务快照。后续编辑原任务，不会重写基线。');row.append(button('冻结本周期基线',a.baseline,'elw-button'),button('生成周会摘要',a.summary,'elw-button elw-primary'));
    const baseline=data.baselines.find(b=>b.id===s.baselineId)||data.baselines.filter(b=>b.period?.start===s.period.start&&b.period?.end===s.period.end).slice(-1)[0];
    if(data.baselines.length){const select=el('select','elw-select');select.setAttribute('aria-label','选择基线');const opt=el('option','','选择基线');opt.value='';select.append(opt);data.baselines.forEach(b=>{const o=el('option','',`${b.name} · ${b.createdAt.slice(0,10)}`);o.value=b.id;select.append(o)});select.value=baseline?.id||'';select.addEventListener('change',()=>a.chooseBaseline(select.value));main.append(select);}
    if(baseline){const comparison=compareBaseline(baseline,data.tasks);const promised=baseline.tasks.filter(t=>t.status!=='cancelled');const closed=promised.filter(t=>{const current=data.tasks.find(c=>c.id===t.id);return current&&current.status!=='cancelled'&&isClosed(current,s.settings.closureStatus)});const metrics=el('div','elw-metrics');metric(metrics,'原承诺',String(promised.length),baseline.name);metric(metrics,'承诺闭环',`${closed.length} / ${promised.length}`,`按${STATUS_LABEL[s.settings.closureStatus]}口径`);metric(metrics,'新增范围',String(comparison.added),'不纳入原承诺分母');metric(metrics,'预测延后',String(comparison.slipped),'对比冻结时的预测日期','is-attention');main.append(metrics);const panel=el('section','elw-panel');heading(panel,'偏差与复盘');if(!comparison.changes.length)paragraph(panel,'当前记录与基线一致。');comparison.changes.forEach(change=>{const task=data.tasks.find(t=>t.id===change.taskId)||baseline.tasks.find(t=>t.id===change.taskId);const line=el('div','elw-baseline-change');line.append(badge(change.type==='added'?'新增范围':change.type==='removed'?'移出 / 缺失':'发生变化'),el('strong','',task?.title||change.taskId),el('span','elw-muted',change.type==='changed'?change.fields.map(f=>`${f.field}: ${String(f.baseline)} → ${String(f.current)}`).join(' · '):change.taskId));panel.append(line);});paragraph(panel,`基线冻结于 ${baseline.createdAt}。复盘应解释变化原因、影响与下一步，而非只比较完成率。`,'elw-note');if(baseline.path)panel.append(button('查看冻结基线 ↗',()=>a.open(baseline.path),'elw-text-button'));main.append(panel);}else empty(main,'先保留一份本周承诺','冻结前可预览任务列表。之后的临时插入、取消和预测变化会单独显示。');
    heading(main,'本周期计划任务');taskTable(main,filtered.filter(t=>taskTouchesPeriod(t,s.period)),data,a);
  }
  const footer=el('footer','elw-footer');footer.append(el('span','','研发负责人工作台 · v0.1.0'),el('span','',`闭环口径：${STATUS_LABEL[s.settings.closureStatus]} · 所有预测需复核前提`));main.append(footer);
}
